### ISSUE TITLE
Recommendation: Rename NuGet Packages

### ISSUE THREAD

**Issue by jamesmontemagno** [EgorBo/Toasts.Forms.Plugin#1]
Wondering if you could update the name of the package to "Toasts Plugin for Xamarin.Forms". Will help with discoverability and things we will be doing to highlight plugins.

Thanks! and this is awesome.

**Comment by EgorBo** [comment]
@jamesmontemagno sure!

**Comment by jamesmontemagno** [comment]
NICE :)
