### ISSUE TITLE
Update NuGet with Unified iOS support 

### ISSUE THREAD

**Issue by jamesmontemagno** [EgorBo/Toasts.Forms.Plugin#10]
Hey there! With 1.3.1 now on stable with Unified support it would be great if you could update the plugin with this support. I created a short How To video on how to do this: https://www.youtube.com/watch?v=nF8DbL-PVKw

**Comment by TorbenK** [comment]
Good stuff. 

I updated this for Xamarin 1.3.1 and the unified api. You can get it here if you cant wait till EgorBo updated his nuget package:

https://github.com/TorbenK/Toasts.Forms.Plugin

**Comment by EgorBo** [comment]
I have just published 1.0.0.6 for 1.3.1 :-) I'm sorry for the delay.
