### ISSUE TITLE
iOS backwards compat

### ISSUE THREAD

**Issue by hardcodet** [EgorBo/Toasts.Forms.Plugin#100]
Hi there

> iOS Support Version 3+ of this plugin requires iOS10 to display the toast notification. If you require support for iOS7+ then please use version 2.0.4. I you want to use the latest plugin with a version less than iOS 10 you can hook into the ReceivedLocalNotification in the AppDelegate to display an Alert.

Sounds like I have two options:
- Richer experience provided by 2.0.4 for older devices, too. This sounds like the way to go today (or are there any downsides with iOS 10 or Android?). That also sounds like a risky one with regards to maintenance.
- Use the latest version of the library and find a way to not degrade the UX for 20% of potential iOS users. What is your recommended pattern/framework to provide users on <iOS 10 with a rich user experience that would play nice with your framework?

Thanks,
Philipp

**Comment by adamped** [comment]
Hi Philipp

Apologies for the delay. I did have an idea of putting the old version back in iOS to handle v9 and below but I never seem to get enough coding time these days.

Unfortunately I don't have any other solution than to download the previous source code for the toasts and implement it yourself for iOS9.

Thanks
Adam
