### ISSUE TITLE
Where is ToastNotification or IToastNotification?

### ISSUE THREAD

**Issue by erportico** [EgorBo/Toasts.Forms.Plugin#101]
Hi guys,
I used your plugin in a project and it was working fine. I added it in a new project but I can't find _ToastNotification_ or _ IToastNotification_ and the toast doesn't appear.

My Xamarin.Forms version is 2.3.2.127 and your component is 1.0.1

I tried to add this code in the iOS AppDelegate.cs

    DependencyService.Register<Plugin.Toasts.CrossToasts>();
    Plugin.Toasts.ToastsImplementation.Init();

but obviously it doesn't work. I tried to change my static method but IToasts it doesn't work.

    public static async Task ShowToast(ToastNotificationType type, string title, string description) {
        var notificator = DependencyService.Get<Plugin.Toasts.Abstractions.IToasts>();
        if (notificator != null) {
            bool tapped = await notificator.Notify(type, title, description, TimeSpan.FromSeconds(2));
        }
    }

Original code

    public static async void ShowToast(ToastNotificationType type, string title, string description) {
        var notificator = DependencyService.Get<IToastNotificator>();
        if (notificator != null) {
            bool tapped = await notificator.Notify(type, title, description, TimeSpan.FromSeconds(2));
        }
    }

Thank you in advance.

**Comment by adamped** [comment]
Hi @erportico 

Please look at the readme file: https://github.com/EgorBo/Toasts.Forms.Plugin

It will walk you through how to set everything up. I think you might have used another plugin at some point as you are referencing Plugin.Toasts.CrossToasts. This is a namespace we have never used.

Thanks
Adam

**Comment by ronakshethia** [comment]
even i am facing the same issue
