### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by erportico** [EgorBo/Toasts.Forms.Plugin#102]
Hi Egor,
when I try to add your component to my project I receive this error:

> Attempting to gather dependency information for package 'Toasts.Forms.Plugin.3.1.0' with respect to project 'myInventories', targeting '.NETPortable,Version=v4.5,Profile=Profile111'
> Attempting to resolve dependencies for package 'Toasts.Forms.Plugin.3.1.0' with DependencyBehavior 'Lowest'
> Resolving actions to install package 'Toasts.Forms.Plugin.3.1.0'
> Resolved actions to install package 'Toasts.Forms.Plugin.3.1.0'
> For adding package 'Toasts.Forms.Plugin.3.1.0' to project 'myInventories' that targets 'portable45-net45+win8+wpa81'.
> Install failed. Rolling back...
> Package 'Toasts.Forms.Plugin.3.1.0' does not exist in project 'myInventories'
> Could not install package 'Toasts.Forms.Plugin 3.1.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

In my previous project I used _PCL 4.5 - Profile 78_ and it's working fine. Thank you in advance

**Comment by erportico** [comment]
I installed version 2.0.4 and it's working fine

**Comment by Rob-Houweling** [comment]
I can confirm the findings above.

**Comment by adamped** [comment]
Version 3 and higher technically only supports .net standard 1.1 and higher. The recommended approach is to stay on 2.0.4 if you havent upgraded to .net standard.

**Comment by erportico** [comment]
Thank you for your comment. Can I update my project to .NET standard 1.1? In my project option the max PCL version is 4.6 
![screen shot 2016-11-11 at 09 22 16](https://cloud.githubusercontent.com/assets/19671573/20210239/60a5ebb0-a7f0-11e6-88d3-1e44ae1cc755.png)

![screen-shot-2016-11-11-at-09 20 13](https://cloud.githubusercontent.com/assets/19671573/20210217/399e2ee2-a7f0-11e6-9501-2f3c6adbc46b.jpg)

**Comment by adamped** [comment]
Have you tried with Toasts version 3.1.1 (released today) on Profile 111. You might be able to get away with that.

**Comment by erportico** [comment]
No, I'll try immediately. Thank you!

**Comment by erportico** [comment]
The problem is still there

> Attempting to gather dependency information for multiple packages with respect to project 'myInventories', targeting '.NETPortable,Version=v4.5,Profile=Profile111'
> Attempting to resolve dependencies for multiple packages.
> Resolving actions install multiple packages
> Removed package 'Toasts.Forms.Plugin 2.0.4' from 'packages.config'
> Added file 'packages.config' to project 'myInventories'.
> Removed reference 'Toasts.Forms.Plugin.Abstractions' from project 'myInventories'.
> Successfully uninstalled 'Toasts.Forms.Plugin 2.0.4' from myInventories
>   GET https://www.nuget.org/api/v2/Packages(Id='Toasts.Forms.Plugin',Version='3.1.1')
>   OK https://www.nuget.org/api/v2/Packages(Id='Toasts.Forms.Plugin',Version='3.1.1') 422ms
>   GET https://www.nuget.org/api/v2/package/Toasts.Forms.Plugin/3.1.1
>   OK https://www.nuget.org/api/v2/package/Toasts.Forms.Plugin/3.1.1 1373ms
> Acquiring lock for the installation of Toasts.Forms.Plugin 3.1.1
> Acquired lock for the installation of Toasts.Forms.Plugin 3.1.1
> Installing Toasts.Forms.Plugin 3.1.1.
> Completed installation of Toasts.Forms.Plugin 3.1.1
> For adding package 'Toasts.Forms.Plugin.3.1.1' to project 'myInventories' that targets 'portable45-net45+win8+wpa81'.
> Install failed. Rolling back...
> Package 'Toasts.Forms.Plugin 3.1.1' does not exist in project 'myInventories'
> For adding package 'Toasts.Forms.Plugin 2.0.4' to project 'myInventories' that targets 'portable45-net45+win8+wpa81'.
> For adding package 'Toasts.Forms.Plugin 2.0.4' to project 'myInventories' that targets 'portable45-net45+win8+wpa81'.
> Package 'Toasts.Forms.Plugin 2.0.4' already exists in folder '/Users/enricorossini/Projects/myInventories/packages'
> Added reference 'Toasts.Forms.Plugin.Abstractions' to project 'myInventories'.
> Added package 'Toasts.Forms.Plugin 2.0.4' to 'packages.config'
> Added file 'packages.config' to project 'myInventories'.
> Package 'Toasts.Forms.Plugin 3.1.1' does not exist in folder '/Users/enricorossini/Projects/myInventories/packages'
> Could not install package 'Toasts.Forms.Plugin 3.1.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
