### ISSUE TITLE
What happened to the styles ?

### ISSUE THREAD

**Issue by NVentimiglia** [EgorBo/Toasts.Forms.Plugin#103]
V2 had a really nice style associated with the toast. I could easily display warnings, errors, and success messages to my user. With V3 the API is completely different and there are no clear instructions on how I can replicate this functionality.

**Comment by adamped** [comment]
In order to bring the toast notifications in line with the native functionality, it now uses the native toasts function. However this brings very limited styling options. If you need the styling, I would stick with v2.0.4 for now.
