### ISSUE TITLE
How to show as snackbar

### ISSUE THREAD

**Issue by resper** [EgorBo/Toasts.Forms.Plugin#104]
Hello,

in your code I found some hints, that is it possible to show the notification on Android as Snackbar.
How can I use this? Or is it currently not possible?

**Comment by adamped** [comment]
@resper - yes you can either set the PlatformOptions > NotificationStyle to make it a default for your app, or on a per notification option by setting the style in the NotificatonOptions and AndroidOptions

**Comment by resper** [comment]
@adamped thx for your answer, I am new with Xamarin and Visual Studio, where I can set this Preference? 
I just found this: https://developer.xamarin.com/guides/android/application_fundamentals/notifications/local_notifications_in_android/

**Comment by gaminn** [comment]
HI, I have Toasts.Forms.Plugin 3.0.0. There is no option to show toast as snackbar in AndroidOptions. How to do that (I don't want to set this for app but per toast)?

Also, is it possible to disable sound for the toast? I'm just displaying information about file being saved and I don't want to disturb user with any sound when displaying the toast.

And is it possible to set timeout for the toast?

**Comment by adamped** [comment]
@gaminn - When you do your Init in Android, there is a PlatformOptions value you can pass through. Set NotificationStyle to Snackbar to make all your toasts use the Snackbar

**Comment by leninweblb** [comment]
Hi adamped, firstly thx for the plugin.
How can I set "Style" inside NotificatonOptions nor AndroidOptions?
