### ISSUE TITLE
Project.json

### ISSUE THREAD

**Issue by TimBarton** [EgorBo/Toasts.Forms.Plugin#105]
Since project.json is getting phased out, will you go back to supporting all targetframeworks?

Thanks

https://www.stevejgordon.co.uk/project-json-replaced-by-csproj

**Comment by adamped** [comment]
The move back to csproj from project.json doesn't change the targetframework support. The toasts plugin will still support .NET Standard 1.1, which is almost every platform except Windows 8.1 SL.
