### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by acaliaro** [EgorBo/Toasts.Forms.Plugin#106]
Hi @EgorBo I have this problem with a new Xamarin Forms project

Could not install package 'Toasts.Forms.Plugin 3.1.2'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by adamped** [comment]
Hi @acaliaro 
You need to use Profile111 or . NetStandard1.1 (or above) to install. It doesn't support Windows Phone Silverlight, which is why it will fail on a Profile259.

**Comment by acaliaro** [comment]
yes Adam. But if I set Profile111, other packages (PropertyChanged.Fody for example) don't work

**Comment by adamped** [comment]
@acaliaro - then using version 2.0.4 is the only option left. This package support PCL Profile 111 or .NET Standard 1.1 and above. If you convert your app to .NET Standard, you can use the imports section in the project.json to add in Fody. However, it can be a bit of effort to change an existing project over.
