### ISSUE TITLE
Set timeout of notification

### ISSUE THREAD

**Issue by deextercz** [EgorBo/Toasts.Forms.Plugin#107]
Hello,
I am trying to set how long should be notification displayed, but I can find anything to set it.
Could you help me with that?

**Comment by adamped** [comment]
Hi @deextercz - There is nothing in the 3.0+ version that lets you control how long it can be shown. Most platforms don't let you change this setting. If you need to ensure the user sees something, it might be best to show them an Alert instead.

**Comment by hemanthme** [comment]
Is there any way we could make the toast to display for 5 seconds. Right now it only displays for 2-3 seconds tops.
