### ISSUE TITLE
The 'await' operator can only be used when its containing method is marked with the 'async' modifier

### ISSUE THREAD

**Issue by Zaxter** [EgorBo/Toasts.Forms.Plugin#11]
I was using the latest Toasts.Forms.Plugin in a shared asset project, trying the sample code you provided.

`var notificator = DependencyService.Get<IToastNotificator>();`
`bool tapped = await notificator.Notify(ToastNotificationType.Error, 
    "Error", "Something went wrong", TimeSpan.FromSeconds(2));`

But this gives me the following error,

`Error CS4033: The 'await' operator can only be used when its containing method is marked with the 'async' modifier (CS4033) (iRemote.iOS)`

However, when I change the code to:

`var notificator = DependencyService.Get<IToastNotificator>();`
`var tapped = notificator.Notify(ToastNotificationType.Error, 
    "Error", "Something went wrong", TimeSpan.FromSeconds(2));`

It works fine, although the **dismiss on click doesn't work on Android** (works fine in iOS).

Could you please direct me as to what I've done wrong?

**Comment by TorbenK** [comment]
It's an async implementation so if you don't call wait it will not wait till the function finished, it will run asynchron.

I just had a quick look into the code but I didn't actually tried to reproduce your problem. I think there is no implementation for an automatic dismiss on click in Android. It just returns true if it's clicked, on iOS the message gets also removed. Anyway, it shouldnt be that hard to implement. You can probably forward the click event to the manager in the Android implementation and then send the REMOVE_CROUTON message with the sender crouton.

**Comment by Zaxter** [comment]
Thanks for replying @TorbenK . The await problem was because I hadn't defined my showToast() method as async. 
For the dismiss onClick in android, I actually downloaded your source code and modified the Crouton.cs file to hide it in the onClick(). I'm a newbie to xamarin and c#, could you elaborate/redirect me to a resource to do this in the way you have suggested?

**Comment by TorbenK** [comment]
I added it, I just did minor testing. You can get it here:

https://github.com/TorbenK/Toasts.Forms.Plugin

**Comment by Zaxter** [comment]
Thanks a lot @TorbenK !

**Comment by De4th69** [comment]
@TorbenK could you release your package on Nuget?

**Comment by TorbenK** [comment]
it is on nuget, but without the android dismiss functionality.

i can update the package next days.

https://www.nuget.org/packages/Toasts.Forms.Plugin.Xamarin.1.3.1/

**Comment by EgorBo** [comment]
I updated my package on the nuget to 1.0.0.7 with dismiss functionality, @TorbenK thanks for handling issues while I was offline :+1:
