### ISSUE TITLE
Custom image

### ISSUE THREAD

**Issue by erportico** [EgorBo/Toasts.Forms.Plugin#110]
Hi,
I have a question about image. Is it possible to custom the image in the toast?

I tried to add in my portable project 

```
AndroidOptions androidOpt = new AndroidOptions() {
    SmallDrawableIcon = 2130772038,
};

var options = new NotificationOptions() {
    Title = title,
    Description = description,
    AndroidOptions = androidOpt,
};
```
but an error occurs

![capture](https://cloud.githubusercontent.com/assets/19671573/22833163/c4a35c10-efa8-11e6-9867-977f6ddd56ce.PNG)

Thanks

**Comment by adamped** [comment]
This will most likely be because the resource isn't available. Have you tried using Android.Resource.{IconName} rather than an int.
