### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by Redunca** [EgorBo/Toasts.Forms.Plugin#111]
Hello,

When i'm running the command, I get this error message : 

```
Install-Package : Could not install package 'Toasts.Forms.Plugin 3.1.4'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain 
any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package Toasts.Forms.Plugin
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

What should I do ? Thank you !

**Comment by adamped** [comment]
@Redunca - You will need to install it on a project that is .NET Standard 1.1+ or Profile111.

To make your project Profile111, remove the Windows Phone Silverlight checkbox, when you go into the properties of your project and look at your target section. If you are using Xamarin Studio, I think it mentions which Profile Number in a drop down box.
