### ISSUE TITLE
FireDate/ Time

### ISSUE THREAD

**Issue by LukasThijs** [EgorBo/Toasts.Forms.Plugin#112]
Hey,

First of all great nuget package very impressed about the entire package 👍 

I have a qeustion about this plugin is there a possible way to configure the notification to show/execute on a certain date?

I didn't find any property associated with this so I do hope that I could get any help creating this 

Thanks in advance!

Luuk

**Comment by adamped** [comment]
This isn't possible at the moment, but it could be added in, the native platform does support it. I will leave this open and see if I can look at this, on the weekend, when not at work,

**Comment by LukasThijs** [comment]
Take your time! greatly appreciated that you would even consider this addition 👍 

Thanks in advance,

Luuk

**Comment by adamped** [comment]
@LukasThijs - I have implemented this in 3.2.0-beta1. Try it out and let me know how it goes: https://www.nuget.org/packages/Toasts.Forms.Plugin/3.2.0-beta1

Use the DelayUntil property in the NotificationOptions to set when you want it displayed.

**Comment by LukasThijs** [comment]
@adamped 

I can confirm that the DelayUntil property works 👍 !

Thanks alot for the time you took developing this it's greatly appreciated :)!

Luuk

**Comment by 1xo2** [comment]
on android 5.1 device DelayUntil  not working
