### ISSUE TITLE
Anyway to wrap text longer? After 1 line it gets cut off.

### ISSUE THREAD

**Issue by jamesmontemagno** [EgorBo/Toasts.Forms.Plugin#116]

**Comment by adamped** [comment]
Which field, Title or Description? Is it every platform or just one?

**Comment by jamesmontemagno** [comment]
Description field. On Both iOS and Android it seems to do it.

**Comment by adamped** [comment]
iOS it was showing multiple lines. Android it was only showing 1 line. I have enabled BigViewStyles on Android, and in the Notification Center, it now shows multiple lines. However in the HeadsUp notification, this is still limited to 1 line and there seems no way to expand this, from my initial research. BigViewStyles are enabled in package version 3.2.0

**Comment by zimmerrol** [comment]
In version 3.2.1 the description is still cut after one line on Android. Instead of a second line, there will be only three dots ("...") at the end of the first line. Is there anything you have to change property/setting-wise to get it work with multiple lines?
