### ISSUE TITLE
Not compatible with Xamarin Android

### ISSUE THREAD

**Issue by breyed** [EgorBo/Toasts.Forms.Plugin#117]
There seems to be a compatibility issue with this library and the latest Xamarin Android build environment.

### Environment
* VS2017
* Xamarain.Android SDK 7.2.0.7
* JDK: 1.8.0_112 (latest installed via VS2017)
* Android NDK: r13b (latest installed via VS2017)
* Android SDK: 7.1 (latest installed via Android Studio)

### Repro
1. Create new project: Blank App (Android)
2. Install-Package Toasts.Forms.Plugin -DependencyVersion Highest
3. Build

### Results
Lots of warnings like this:
>warning XA0106: Skipping TestToast.Resource.Animation.design_bottom_sheet_slide_in. Please check that your Nuget Package versions are compatible.

And this error:
```
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1399,2): error : Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Xamarin.Android.Support.Design, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1399,2): error : File name: 'Xamarin.Android.Support.Design.dll'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1399,2): error :    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1399,2): error :    at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1399,2): error :    at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)

```

**Comment by adamped** [comment]
@breyed - Try installing Xamarin.Android.Support.Design from Nuget. It looks like I am missing a dependency from the nuspec. If that also works for you, I will update and publish a new package.

**Comment by breyed** [comment]
Adding Xamarin.Android.Support.Design resolved the issue.
