### ISSUE TITLE
Change text colour on iOS in version 2.0.4

### ISSUE THREAD

**Issue by sander1095** [EgorBo/Toasts.Forms.Plugin#118]
Hello! 

I am using this plugin (version 2.0.4) and I am displaying a toast with a yellow background. I apparently cannot change the text colour on iOS (Haven't tested on Android yet) and that is really annoying because `MessageView` has private properties for it:

    private static readonly UIColor TitleColor;
    private static readonly UIColor DescriptionColor;

I have tried to find a working commit of version 2.0.4 so I can modify the plugin myself so I can do what I want, but no commit of version 2.0.4. is available... and other versions that seem like they are version 2.0.4.  (https://github.com/EgorBo/Toasts.Forms.Plugin/tree/6e6c4271de23ffed73381c3aadacc90f3bd1c128) do not seem to build because they were pushed before they were tested.

Can someone tell me how I could change the text colour or can someone point me to a commit that allows me to modify the 2.0.4. version?

**Comment by sander1095** [comment]
@EgorBo @adamped I would love some help with this :)

**Comment by Boeves** [comment]
@EgorBo @adamped I have the same issue.

**Comment by adamped** [comment]
@sander1095 @Boeves - its been a while, but can you change it via a custom renderer. You can view this old version of the Readme for an example: https://github.com/EgorBo/Toasts.Forms.Plugin/blob/6ac9479c86d39d1eb8d5026bdb1fc10e14ec0acb/README.md

**Comment by sander1095** [comment]
Not for iOS. 

1. On iOS a class has to be created [inherits from `MessageBarStyleSheet`. ](https://github.com/EgorBo/Toasts.Forms.Plugin/issues/32#issuecomment-118843980) 

2. Then you can override 3 methods:
* BackgroundColorForMessageType()
* IconImageForMessageType()
* StrokeColorFOrMessageType()

There is nothing that can be done to change the text color. The text color is defined in `MessageView` which cannot be changed. The example in the readme is for Windows phone.

------
On Android it isn't possible either I think, I have to inherit from `IToastLayoutCustomRenderer` and then fill the `Render` method. I do not know much about the `View` class on Android but I cannot see a `SetTextColor` method or something like that.

**Comment by adamped** [comment]
Unfortunately I can not help with this because the version is very outdated, and no longer supported. You will have to download the source code for that version and modify yourself to get this feature.

**Comment by sander1095** [comment]
Downloading the source code is tricky because there is no commit related to 2.0.4. Can you help with this?

In the future, add a version identifier to commits or make use of the Releases system in Github? Finding specific versions is not an easy task in this repo..

The only version close to the release of 2.0.4 is 
https://github.com/EgorBo/Toasts.Forms.Plugin/tree/6e6c4271de23ffed73381c3aadacc90f3bd1c128

That version is not usable because before it was committed it wasn't built to see if it worked. It doesn't. Files are missing and that is why I opened the issue.

**Comment by adamped** [comment]
I have a forked repo at 2.0.4: https://github.com/adamped/Toasts.Forms.Plugin

**Comment by sander1095** [comment]
Thanks!
