### ISSUE TITLE
WP8 solution does not build with XF 1.3.2

### ISSUE THREAD

**Issue by Frounz** [EgorBo/Toasts.Forms.Plugin#12]
After upgrade of Xamarin.Forms to 1.3.2  the WP8 solution does not build anymore because of missing  dependency to XF 1.3.1.  Android and iOS build fine.

any workaround ?

**Comment by MichaelRumpler** [comment]
Thats the same as https://github.com/EgorBo/Toasts.Forms.Plugin/issues/5. Toasts needs to be built with the new version again.

**Comment by EgorBo** [comment]
I've just updated nuget package to 1.0.0.8 with XF 1.3.2 support.

**Comment by Frounz** [comment]
Thanks !
