### ISSUE TITLE
How do I use this plugin in Xamarin Forms?

### ISSUE THREAD

**Issue by AugustoCV** [EgorBo/Toasts.Forms.Plugin#120]
I've followed the README.md and added the DependencyService registration in my AppDelegate.cs as well as the permissions required for iOS. My issue happens when I try to get the DependencyService to resolve IToastNotificator in my Xamarin.Forms project I get the error:

"The type or namespace IToastNotificator) could not be found"

Indeed, the namespace Plugin.Toasts cannot be referenced in my source code with the directive using either even though the Toast.Forms.Plugin is installed and listed in my portable project. Is there any step that I am missing? Adding those lines in AppDelegate.cs was all that was needed to make use of the plugin in the Xamarin.Forms project?

**Comment by cdrwolfe** [comment]
Make sure you have both the standard toast plugin and the PCL one. I use 'Using Plugin.Toasts;' for both droid and iOS, it should work.
