### ISSUE TITLE
No way to set notification type?

### ISSUE THREAD

**Issue by Zoso221** [EgorBo/Toasts.Forms.Plugin#122]
In a previous version of the library, there seems to be a ToastNotificationType enum that you could pass in to the Notify method to choose an error or warning.

Is this functionality no longer present or is there a new method?  Forgive me if I have missed something...

thank you

**Comment by adamped** [comment]
That ended in version 2.0.4. The plugin switched to use the native toast/notification API's. You can set the icon yourself, changing colors as previously done, is no longer possible.
