### ISSUE TITLE
Feature request: Possibility to disable Auto Timeout

### ISSUE THREAD

**Issue by Mr-Pearce** [EgorBo/Toasts.Forms.Plugin#124]
currently when i use
`.Notify(Callback, options);`
The callback is triggered after 7 seconds with the callback result Action `NotificationAction.Timeout`
Even when `IsClickable ` is set to true in the `NotificationOptions`.

Because of that behavior after 7 seconds the notification is not able to react to that click event properly.

**Comment by adamped** [comment]
The notification should disappear after 7 seconds, hence they would be unable to click it. Is it possible to extend the time the notification appears, and is this happening for you?

**Comment by Mr-Pearce** [comment]
I have the following situation. (on Ios but probably same on Android)

- i get a notification.
- the notification shows up in front (clickable)
- the notification disappears from front to tray after few seconds(7?)
(and gets Timeout which executes its Action(with timeout result)) 
- when i open the notificationTray and click on that notification, the notification (click) action is not executed because its already executed with an Time Out

Without that 7 second "AutoTimeOut" it would be possible to get the click Event from notifications that are stored in the notificationTray.

**Comment by adamped** [comment]
Sorry, but when the notification closes, it goes to the notification center. From there, the app can't access it. When you click on the notification from there, you can only know you clicked on it by overriding DidReceiveRemoteNotification in the iOS AppDelegate.cs.
