### ISSUE TITLE
Android: Nothing happens when tapping on a notification in the drawer

### ISSUE THREAD

**Issue by NxSoftware** [EgorBo/Toasts.Forms.Plugin#127]
I've seen #123 but this seems to be a different issue...

**Steps to reproduce:**
- Display a notification.
- Wait for it to disappear.
- Pull down the notification drawer.
- Tap on the notification

**Expected results**
The callback passed to `ToastNotification.Notify` should be called.

**Actual results**
Nothing happens.

**Device**
Google Pixel XL running Android 7.1.2

--

This seems to be due to the notification timing out when it disappears, triggering the `ManualResetEvent` and disposing of the pending click and dismiss intents.

**Comment by elneilios** [comment]
Is there going to be a fix or workaround for this?

**Comment by AlcantaraRW** [comment]
Same issue here. Any fix?

**Comment by adamped** [comment]
Fixed in 3.3.0-pre1
