### ISSUE TITLE
Show more than one at a time

### ISSUE THREAD

**Issue by TravyDale** [EgorBo/Toasts.Forms.Plugin#128]
I thought it was possible to show more than one toast at a time. Is this possible at all? Anything I try, it always seems to do them synchronous (one after another). 

If it helps, I am using version 2.0.4 due to the iOS10 stipulation you mentioned in your readme.

**Comment by adamped** [comment]
@TravyDale - It is possible on Windows Phone on that version, but not on iOS or Android.
