### ISSUE TITLE
Unhandled Exception under Xamarin.iOS

### ISSUE THREAD

**Issue by De4th69** [EgorBo/Toasts.Forms.Plugin#13]
I'm using your latest version of this plugin and under iOS I don't get it to work. It always throws an unhandled exception, which I can't catch, without any information.

I'm running Xamarin.Forms 1.3.1 in the TestApplication I made to show the problem.
In this code it doesn't even execute the button clicked event. Am I doing something wrong?

I noticed, that when I install the plugin via nuget package manager, in the iOS project the wrong ```Toast.Forms.Plugin.Abstractions.dll``` gets referenced (its referencing the pcl version) and the ```Toast.Forms.Plugin.iOS.dll``` is not referenced at all. So I added them by myself. May this be the problem?

```
AppDelegate.cs



using Foundation;
using Toasts.Forms.Plugin.iOS;
using UIKit;

namespace XFTest.iOS
{
    [Register("AppDelegate")]
    public partial class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate
    {
        public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            global::Xamarin.Forms.Forms.Init();
            ToastNotificatorImplementation.Init();
            LoadApplication(new App());

            return base.FinishedLaunching(app, options);
        }
    }
}
```

```
App.cs

using Xamarin.Forms;

namespace XFTest
{
    public class App : Application
    {
        public App()
        {                       
            // The root page of your application
            MainPage = new TestPage();
        }
    }
}
```

```
TestPage.cs

using Toasts.Forms.Plugin.Abstractions;
using Xamarin.Forms;

namespace XFTest
{
    public class TestPage : ContentPage
    {
        public TestPage()
        {
            var layout = new StackLayout();
          
            var button = new Button
            {
                Text = "Notifier"
            };
            button.Clicked += ButtonOnClicked;

            layout.Children.Add(button);

            Content = layout;
        }

        private async void ButtonOnClicked(object sender, EventArgs eventArgs)
        {
            var notifier = DependencyService.Get<IToastNotificator>();

            bool tapped = await notifier.Notify(ToastNotificationType.Info, "Test", "test", TimeSpan.FromSeconds(5));
        }
    }
}
```

///Edit: I installed it with the console and now I get this exception:

```System.NotImplementedException: The requested feature is not implemented```

The ```Toasts.Forms.Plugin.Abstractions.dll``` is referenced wrong again. It's the PCL profile one. Not the Monotouch10.

///Edit2: When I add the correct references the ```DependecyService.Get``` is working. But when I try to display an toast notification I get an ```Unhandled.Exception``` of type ```System.NullReferenceExcpetion: Object reference not set to an instance of an object```

**Comment by EgorBo** [comment]
seems like incorrect nuget package, it doesn't add a reference to Toasts.Forms.Plugin.iOS.dll for ios project. I'll release 1.0.0.10 once I find the reason why.

**Comment by De4th69** [comment]
@EgorBo I tested 1.0.0.11 and in my Test Project it works. I'm gonna test it in my actual application now

**Comment by EgorBo** [comment]
@De4th69 there is already 1.0.1.12 with small fix for ios (in some cases description may disappear)
