### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ptrkseg** [EgorBo/Toasts.Forms.Plugin#131]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Toasts.Forms.Plugin 3.2.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by adamped** [comment]
The toasts plugin is .NET Standard. You need to update your project to .NET Standard, or I think you can install it, if you change your PCL to Profile111. https://xamarinhelp.com/upgrade-pcl-net-standard-class-library/
