### ISSUE TITLE
Feature request: Configurable snackbar notification duration

### ISSUE THREAD

**Issue by pdunlop** [EgorBo/Toasts.Forms.Plugin#132]
Currently, `SnackbarNotification.Notify(...)` calls `Snackbar.Make` with `Snackbar.LengthLong`.

It would be useful to be able to pass in an optional overriding `TimeSpan` to control how long the notification is displayed for before it is automatically dismissed.

**Comment by adamped** [comment]
@pdunlop this is controlled via the OS, I have no or limited control over this, depending upon platform.

**Comment by pdunlop** [comment]
@adamped I've taken a closer look, and there is a call in `SnackbarNotification`:
```
var snackbar = Snackbar.Make(view, builder, Snackbar.LengthLong);
```

Replacing `Snackbar.LengthLong` with number of milliseconds does extend the duration, so
```
var snackbar = Snackbar.Make(view, builder, 10000);
```
displays for 10 seconds (for Android at least).

Would you consider passing an optional duration in the options to configure this?
Thanks.
