### ISSUE TITLE
Failed to install nuget package on Xamarin Forms PCL project

### ISSUE THREAD

**Issue by R3muSGFX** [EgorBo/Toasts.Forms.Plugin#138]
Hello.
I tried to install this nuget package to my Xamarin Forms projects (PCL) and the nuget manager returned with this error:

> Could not install package 'Toasts.Forms.Plugin 3.2.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

After further research I saw that the packages were installed for the iOS, Android and UWP projects but not for the PCL project.
Am I doing something wrong ? 
Thanks in advance.

**Comment by adamped** [comment]
This plugin only support .NET Standard 1.1 or higher. Update your PCL to .NET Standard. https://xamarinhelp.com/upgrade-pcl-net-standard-class-library/
