### ISSUE TITLE
Toast Colors

### ISSUE THREAD

**Issue by douglassimaodev** [EgorBo/Toasts.Forms.Plugin#139]
How to set the color to be green for success, blue for alert and red for error as here : https://xamarinhelp.com/toasts-plugin-for-xamarin-and-windows/

Also where is the project files for this demo from this link?

**Comment by adamped** [comment]
That is only with version 2.0.4 which is no longer supported. Version 3.3.0-pre1 can set the text color on an Android notification, but that is the limits of customization.
