### ISSUE TITLE
override void ReceivedRemoteNotification no longer works

### ISSUE THREAD

**Issue by shaungrech** [EgorBo/Toasts.Forms.Plugin#140]
I would like to use these notifications for Remote Notifications. 

Basically I override the 'ReceivedRemoteNotification' as shown below:

```
public override void ReceivedRemoteNotification(UIApplication application, NSDictionary userInfo)
        {
            ProcessNotification(userInfo, false);
        }
```

I then call a method in my PCL which Creates the Toast as shown below:
```
IToastNotificator notification = DependencyService.Get<IToastNotificator>();
                var result = await notification.Notify(options);
                var t = result.Action;
                if (t == NotificationAction.Clicked)
                {
                    Settings.PendingNotifications = false;
                    actionNotification(pushParam);

                }
                else if (t == NotificationAction.Dismissed)
                {
                    Settings.PendingNotifications = false;
                }
```

After the first toast is created the '**ReceivedRemoteNotification**' no longer works. Is it possible that it is being overridden again by the plugin?

Thanks
Shaun

**Comment by adamped** [comment]
No, the plugin doesn't do anything with the AppDelegate and there is no way for it to override it. If your app is in the background, ReceiveRemoteNotification works. If you click on the notification while your app is in the foreground, then DidReceiveRemoteNotification will be called.
