### ISSUE TITLE
iPhone X notification UI bug

### ISSUE THREAD

**Issue by mindofai** [EgorBo/Toasts.Forms.Plugin#145]
We tested our app in a iPhone X device and as we all know, it disrupts the UI for some apps out there because of its notch. Apparently, the toast plugin also has an issue with the notch. See screenshot below:

![screenshot_246](https://user-images.githubusercontent.com/18261468/34477450-4b8876ca-efd5-11e7-9e94-b138ada65051.png)

Is there any way or config/property to move the notification or are you already working on solution? Thanks!

**Comment by adamped** [comment]
@mindofai - this is using 2.0.4 version of the toasts plugin. This version number is no longer supported.

**Comment by mindofai** [comment]
So, you mean to say that in the latest version of the toasts plugin, this isn't an issue?

**Comment by adamped** [comment]
@mindofai - yes its not an issue, but with version 3.0 it went through a rather large update. And due to switching to native toasts/notifications, it lost the ability to color the notifications on iOS. On Android you can color the text at least.
