### ISSUE TITLE
Set timeout of notification for latest version

### ISSUE THREAD

**Issue by mindofai** [EgorBo/Toasts.Forms.Plugin#146]
How can I set how long the notification will be shown? I want to set it to 10 seconds. I've read an issue about this, but it was more than a year ago. Hopefully, there is a way now. Thanks!

**Comment by adamped** [comment]
@mindofai - in Android there is a way to vary its length, but in iOS there is not. Hence the functionality isn't here to maintain platform consistency. Notifications show for 7 seconds by default.
