### ISSUE TITLE
using Toasts.Forms.Plugin.iOS

### ISSUE THREAD

**Issue by stefan89** [EgorBo/Toasts.Forms.Plugin#15]
"using Toasts.Forms.Plugin.iOS"  can't be resolved within an iOS project. Is this a known issue?

Project info:
Xamarin.Forms v1.3.2
Unified API
Toasts plugin v1.0.0.9

**Comment by EgorBo** [comment]
@stefan89, yes it is, I am trying to fix it.

**Comment by EgorBo** [comment]
Fixed
