### ISSUE TITLE
Method 'Android.App.Notification/Builder.SetChannelId' not found.

### ISSUE THREAD

**Issue by egarim** [EgorBo/Toasts.Forms.Plugin#150]
Hi I got the following error
Method 'Android.App.Notification/Builder.SetChannelId' not found.

when I execute this code 

```
var options = new NotificationOptions()
                    {
                        Title = "Title",
                        Description = "Description"
                    };
                    var result = await notificator.Notify(options);
```
targetSdkVersion="23"
xamarin forms 2.4.0
android build tools 23.0.3
Toast plugin 3.3.0

**Comment by adamped** [comment]
Should be fixed in https://www.nuget.org/packages/Toasts.Forms.Plugin/3.3.1
