### ISSUE TITLE
Icon on android does not show up with Toast notification

### ISSUE THREAD

**Issue by softsan** [EgorBo/Toasts.Forms.Plugin#152]
Hi,

Used Toast notification plugin **(version 3.3.1)** for Xamarin.forms app.

The icon on toast notification does not show up on android. However its working fine on iOS. i double checked the icon and its there in "Resources -> Drawable" folder in my android project.
Please see following  code: 
```
var notificator = DependencyService.Get<IToastNotificator>();
                 
                var options = new NotificationOptions
                {
                    ClearFromHistory = true,
                    AllowTapInNotificationCenter = false,
                    WindowsOptions = new WindowsOptions() { LogoUri = "icon.png" },
                    Description = description,
                };

 var result = notificator.Notify(options);
```
on Android-> Mainactivity

```
DependencyService.Register<ToastNotification>();
ToastNotification.Init(this);
```

**Comment by softsan** [comment]
Any clue or suggestion on this?

**Comment by adamped** [comment]
@softsan - your using WindowsOptions, you need to use AndroidOptions or iOSOptions.
