### ISSUE TITLE
Notification displaying twice

### ISSUE THREAD

**Issue by zBrianW** [EgorBo/Toasts.Forms.Plugin#153]
When the iOS application is open (UIApplicationState.Active) and notification received, only the DidReceiveRemoteNotification is invoked (as expected). However, after this first notification, when subsequent notification is received the native iOS toast message is appearing (as if the application were inactive) as well as the DidReceiveRemoteNotification being invoked which results in 2 notification messages being displayed.

-----------------------------------------------------------------------------------------------------------------
iPhone 8 iOS 11.0.3
Toasts.Forms.Plugin 3.3.1
Xamarin.Forms 2.5.0.91635 (though Toasts.Forms.Plugin only being referenced in our iOS project)

**Comment by adamped** [comment]
This plugin only sends a notification, it doesn't know about application state, nor the state your app will be in when it is received. Hence it is more likely that something in your application is causing this issue, but without seeing it, I wouldn't know what is happening. If you do find out it is an issue with this plugin for some reason that I am not seeing at the moment, please reopen the issue with more details and a reproduction project.
