### ISSUE TITLE
Add support for iOS classic API.

### ISSUE THREAD

**Issue by Indish** [EgorBo/Toasts.Forms.Plugin#16]
Add support for Classic API until we port it to Unified API

We can't test the iOS app as I get the error : 

with version 1.0.0.9 :
cannot include both 'monotouch.dll' and 'xamarin.ios.dll' in the same xamarin.ios project - 'xamarin.ios.dll' is referenced explicitly, while 'monotouch.dll' is referenced by 'toasts.forms.plugin'

with latest stable version,
there is no Toasts.Forms.Plugin.iOS assembly

**Comment by haduyenhoa** [comment]
I have this problem too. I don't know how to fixe that. I can add Toast.Forms.Plugin into .iOS project but in that project, it does not find Toasts.Forms.Plugin.iOS assembly
