### ISSUE TITLE
WP8 solution does not build with XF 1.3.3

### ISSUE THREAD

**Issue by Frounz** [EgorBo/Toasts.Forms.Plugin#18]
Hi @EgorBo !

I REALLY REALLY REALLY like your plugin and it works perfectly, but everytime Xamarin.Forms gets updated, the build for the WP8 version of the app breaks... iOS and Android works perfectly well. 

Is there anything wrong with my setup ?

Thx !

**Comment by EgorBo** [comment]
@Frounz thank you for noticing that, I've just pushed an update to nuget with 1.3.3 support.

**Comment by Frounz** [comment]
wow, you're fast ! :)

I'm planning on testing XF 1.3.4-pre1 because of its support for dymanic sized cells on iOS. Would you have to add support for 1.3.4 again manually ?

**Comment by EgorBo** [comment]
dynamic sized cells -- sounds good, ok, I'll release an update in a hour.

**Comment by EgorBo** [comment]
@Frounz just uploaded 1.0.3.14-pre1 for XF 1.3.4.6325-pre1 (prerelease channel).

**Comment by Frounz** [comment]
hmmmm... WP8 still wants XF 1.3.2...

**Comment by Frounz** [comment]
no hurry... i commented the plugin-related code out for the moment and will upgrade to next stable release of XF and your plugin when available... enough other things to do in the meantime ! ;-)

Thanks for your perfect support !
