### ISSUE TITLE
Toast not shown correctly in landscape mode 

### ISSUE THREAD

**Issue by stefan89** [EgorBo/Toasts.Forms.Plugin#19]
Happens in iOS.

Using latest version of Toasts plugin and latest stable version of Xamarin.Forms

![ios simulator screen shot 20 feb 2015 10 20 54](https://cloud.githubusercontent.com/assets/1457137/6283878/65e45338-b8ea-11e4-9e31-1922f8ba884b.png)

UPDATE:
It seems it only happens incorrect on iOS8+.

**Comment by EgorBo** [comment]
@stefan89 can you please specify the device and its orientation? thanks

**Comment by stefan89** [comment]
Device: iPad 2 and iPad 4
Orientation: landscape

**Comment by EgorBo** [comment]
@stefan89 thanks! i've just reproduced it, trying to fix..

**Comment by stefan89** [comment]
That would be great! Thanks in advance

**Comment by EgorBo** [comment]
@stefan89 can you try  1.0.4.16 package? I believe I've fixed it. It's a well known issue caused by breaking changes in IOS8: http://stackoverflow.com/questions/24150359/is-uiscreen-mainscreen-bounds-size-becoming-orientation-dependent-in-ios8

**Comment by stefan89** [comment]
Excellent work! It is fixed.

Thanks for the quick fix and fast response.
