### ISSUE TITLE
Information Needed For Swag Bag

### ISSUE THREAD

**Issue by jamesmontemagno** [EgorBo/Toasts.Forms.Plugin#2]
I first want to personally thank you for creating a Plugin for Xamarin for our holiday contest. To get your exclusive Xamarin Swag Bag out to you I just need a bit more information from you. If you can email: plugins@xamarin.com with the following information we will get the bag out to you.

Name
Street Address
City, State, Zip Code
Country
Phone Number
The URL to this repo

Thank you again and I hope to see even more plugins from you in the future. Always feel free to reach out if you need anything.

**Comment by EgorBo** [comment]
Thanks!
I look forward to participating new contests!
PS: send an email.
