### ISSUE TITLE
Solution does not build for WP8 with Xamarin.Forms 1.4.0-pre1

### ISSUE THREAD

**Issue by Frounz** [EgorBo/Toasts.Forms.Plugin#20]
hi @EgorBo !

would you mind updating to xamarin.forms 1.4.0-pre1 ?  there are many nice features within this release and xamarin wants to stay with 1.4.0 for future bug fixes, so no one has to update plugins to the latest patch levels...

Thanks !

**Comment by EgorBo** [comment]
@Frounz sorry for the long delay, sure. I've just published 1.1.6.18-pre1 to nuget with XF 1.4.0-pre1 support

**Comment by Frounz** [comment]
thanks !
