### ISSUE TITLE
Type Custom with DefaultToastLayoutRenderer

### ISSUE THREAD

**Issue by christophedelanghe** [EgorBo/Toasts.Forms.Plugin#21]
I implemented the DefaultToastLayoutRenderer with type ToastNotificationType.Custom passing an url (small profile image from web) and a color. 
The problem is it takes a little time to load the image the first time (I cache it for reuse) and while retrieving the image, the default image ("Resource.Drawable.error") is shown.
Could this be changed so that there is no default image when using the Action<object, ImageView> imageSetterForCustomType = null.

Thanks in advance and keep up the good work.

**Comment by adamped** [comment]
Not longer applicable as Toasts Plugin has been rewritten. 

Please file a new issue if you experience an problem with the new version.

More Info: https://xamarinhelp.com/toast-notifications-xamarin-forms/
