### ISSUE TITLE
WP8 solution does not build with XF 1.4.0

### ISSUE THREAD

**Issue by piotrwojtowicz** [EgorBo/Toasts.Forms.Plugin#22]
After upgrade of Xamarin.Forms to 1.4.0 the WP8 solution does not build anymore because of missing dependency to XF 1.3.1. Android and iOS build fine.

Same as:
- https://github.com/EgorBo/Toasts.Forms.Plugin/issues/12
- https://github.com/EgorBo/Toasts.Forms.Plugin/issues/5

Could we have a fix? Thank you for your good work :)

**Comment by Frounz** [comment]
hi @piotrwojtowicz 

use "install-package toasts.forms.plugin -pre" to install the prelease Version of this nuget package. Works perfectly with 1.4.0.

**Comment by piotrwojtowicz** [comment]
Yes, thos version builds correctly, thank you :)
