### ISSUE TITLE
Exception System.MissingMethodException

### ISSUE THREAD

**Issue by armintelker** [EgorBo/Toasts.Forms.Plugin#23]
Hey Egor,
i got this error when I want to use the toast.

Android 4.4/5.0
Xamarin Forms 1.4.0.6341
Toasts.Forms.Plugin 1.0.6.18

```
public static void Error(string text, string description = null, int duration = 3) 
{
    DependencyService.Get<IToastNotificator>().Notify(
       ToastNotificationType.Error, 
       text, 
       description, 
       TimeSpan.FromSeconds(duration)
    );
}
```
 
```$exception	
{System.MissingMethodException: Default constructor not found for type Toasts.Forms.Plugin.Droid.ToastNotificatorImplementation   
at System.Activator.CreateInstance (System.Type type, Boolean nonPublic) [0x00000] in <filename unknown>:0    
at System.Activator.CreateInstance (System.Type type) [0x00000] in <filename unknown>:0    
at Xamarin.Forms.DependencyService.Get[IToastNotificator] (DependencyFetchTarget fetchTarget) [0x00000] in <filename unknown>:0    
at Foo.Common.Views.Toast.Error (System.String text, System.String description, Int32 duration) [0x00002] in /Users/armintelker/git/universal-app/Foo/Common/Views/Toast.cs:21    
at Foo.Green.Search.Pages.ScannerSearchPage+<searchBarcode>c__async0.MoveNext () [0x000d9] in /Users/armintelker/git/universal-app/Foo/Green/Search/Pages/ScannerSearchPage.xaml.cs:111 }	
System.MissingMethodException
```

Do you have maybe a idea?
Thanks :)

**Comment by EgorBo** [comment]
@armintelker, looks like the linker removed that constructor. Do you use "Linking: Sdk and User Assemblies"? Add "new ToastNotificatorImplementation()" to your LinkerPleaseInclude.cs as a temporarily workaround.

**Comment by adamped** [comment]
Can not reproduce. If it is still occurring, please comment with some more information and I will reopen the issue.

**Comment by trevoriancox** [comment]
I'm experiencing this on Nexus 7, Android 4.1.1 with XForms 2.0.1 and Toasts.Forms.Plugin 2.0.0. Fixed using LinkerPleaseInclude with "new ToastNotificatorImplementation()" as per @armintelker .

**Comment by Femilshajin** [comment]
In Linker if I select 'SDK and user assemblies' I'm getting this error.

**Comment by mtsalenc** [comment]
@trevoriancox @EgorBo Could you please elaborate on this? I am experiencing this issue on a Xamarin.Forms PCL project, using Sdk and user assemblies for my android linker options.

Am I supposed to create a class named LinkerPleaseInclude on the android project? Is `"new ToastNotificatorImplementation()` supposed to go inside the constructor of the LinkerPleaseInclude class like this?:

`namespace RCS0500Mobile.Droid
{
    [Android.Runtime.Preserve(AllMembers = true)]
    class LinkerPleaseInclude
    {
        public LinkerPleaseInclude()
        {
            new ToastNotificatorImplementation();
        }
    }
}`

**Comment by sohail585** [comment]
Any solution?
