### ISSUE TITLE
Windows Store

### ISSUE THREAD

**Issue by radderz** [EgorBo/Toasts.Forms.Plugin#25]
Hi,

I like this plugin quite a lot, is there any chance this will or could be extended to the Xamarin.Forms windows store preview?

Cheers

**Comment by ghuntley** [comment]
+1 for WPA81 (ie not silverlight)

**Comment by chbecher** [comment]
+1 WPA81

**Comment by adamped** [comment]
@radderz @ghuntley @chbecher - 2.0.0-pre1 now supports WPA81 and by default UWP.

**Comment by ghuntley** [comment]
Cheers Adam!
