### ISSUE TITLE
iOS truncates text instead of wrapping

### ISSUE THREAD

**Issue by rob-derosa** [EgorBo/Toasts.Forms.Plugin#28]
Can't figure out how to get text to wrap to a 2nd line. Any ideas?

Hoping to use this on an internal project here at Xamarin.

**Comment by djooleean** [comment]
Any news on this ticket ?

What's the actual iOS development status ? 
I have NullReferenceExceptions when I try to use a custom MessageStyleSheet class...

Thanks

**Comment by highplains** [comment]
+1

**Comment by highplains** [comment]
I have found that when building an iOS project with supported architectures set to just "arm7" this problem doesn't exist. But release builds require "arm7 + arm64" for the app store and this seems to cause text to truncate. (Tested on a iPhone 6 Plus)

**Comment by highplains** [comment]
When targeting x64 the methods that use NSString.DrawString need to be converted to the non-deprecated extension methods and then the truncation disappears.

to fix change

Title.DrawString(titleRectangle, TitleFont, UILineBreakMode.TailTruncation, UITextAlignment.Left);
to
Title.DrawString(titleRectangle, new UIStringAttributes { Font = TitleFont, ForegroundColor = TitleColor });

and 
Description.DrawString (descriptionRectangle, DescriptionFont, UILineBreakMode.TailTruncation, UITextAlignment.Left);
to
Description.DrawString(descriptionRectangle, new UIStringAttributes { Font = DescriptionFont, ForegroundColor = DescriptionColor });

Perhaps this has to do with Unified API. See
http://developer.xamarin.com/guides/cross-platform/macios/updating-tips/
Objective-C category methods are now generated as extension methods in the Unified API. For example, code that previously used UIView.DrawString would now reference NSString.DrawString in the Unified API.

**Comment by trevoriancox** [comment]
+1

**Comment by zawadzkip** [comment]
I'm beginning to look more into this issue, @EgorBo you tweeted me some information to use to help reproduce but I have been unable even after switching the build type and trying on an iPhone 6s +/iPhone 6+ any other steps/info someone can provide to help reproduce?

**Comment by adamped** [comment]
@zawadzkip - try building exclusively in ARM64 to see if that replicates it.

**Comment by highplains** [comment]
This was fixed in a diff app that used extremely similar code as yours....

https://github.com/aritchie/userdialogs/issues/55

**Comment by adamped** [comment]
Fixed as of 2.0.0-pre2
