### ISSUE TITLE
Feature request: Is Sticky Mode 

### ISSUE THREAD

**Issue by supreettare** [EgorBo/Toasts.Forms.Plugin#29]
Can we have one more property for IsSticky when set the Toast shows until tapped or until we hide it from code? 
This would be a great feature to have. 

Thanks 
ST

**Comment by supreettare** [comment]
Basically the idea is to show the toast & wait for a certain operation to complete before hiding it. 
Also is there a way I can make the Toast Model? So rest of the UI is blocked for any touch input before the Toast is hidden again? 

Looking forward to your response. 
P.S. This is one of the best libraries I have worked with so far on Xamarin Forms. +1 for an amazing job.

**Comment by adamped** [comment]
Feature was completed.
