### ISSUE TITLE
[Crash] Crash with Xamarin Android

### ISSUE THREAD

**Issue by Zeraceee** [EgorBo/Toasts.Forms.Plugin#3]
http://pastie.org/9823032

**Comment by EgorBo** [comment]
wow, looks like https://bugzilla.xamarin.com/show_bug.cgi?id=17257 
Could you please give more details: device and Android version?
Thanks.

**Comment by Zeraceee** [comment]
Phone:
LG-VS980
Android 4.4.4

Build: 
Compile API 16 (4.1)
Minimum API 16 (4.1)
Target API 20 (4.4.87)

**Comment by Zeraceee** [comment]
Actually, with API 16 I get a nullpointer which looks like this: http://pastie.org/9823440
