### ISSUE TITLE
Please add support to profile 111

### ISSUE THREAD

**Issue by jinlook** [EgorBo/Toasts.Forms.Plugin#31]
Toasts.Forms is a wonderful plugin, but It need profile 259 when I install the plugin. The install failed in my profile 111 PCL project.
Profile 259 lacks of Parallel Tasks, System.IO.Compression and System.Net.Http, those are very useful libraries and I use them in my project. So I have to use profile 111 in my PCL project.
While I'm also eager to use this nice plugin in my project. 
Is it possible to support profile 111?

For the difference of profiles, please refer to http://danrigby.com/2014/04/16/xamarin-pcl-profile-notes/

**Comment by tomcrusader** [comment]
I just ran in to this as well. Don't want to have to clone the project and re-target to Profile 111

**Comment by adamped** [comment]
@jinlook @tomcrusader - I currently don't have the time to ensure the project supports 259 and 111 at the moment, however I am open to a pull request if anyone wants to tackle it.
