### ISSUE TITLE
MessageBarStyleSheet is read only?

### ISSUE THREAD

**Issue by patook** [EgorBo/Toasts.Forms.Plugin#32]
I'm trying to call Init in Xamarin.iOS with ToastNotificatorImplementation.Init(new MessageBarStyleSheet() { ??? } );

However, it looks like none of the parameters of the "custom" style sheet can actually be altered. Am I missing something?

**Comment by djooleean** [comment]
In fact you have to inherit a new class from MessageBarStyleSheet ans use it in your Init method.
Then override the 3 methods:
- BackgroundColorForMessageType( ... )
- IconImageForMessageType( ... )
- StrokeColorForMessageType( ... )

But actually I have a NullReferenceException when I use a custom class... I have to investigate why...

**Comment by sander1095** [comment]
@djooleean have you figured out how to solve the NullReferenceException?
