### ISSUE TITLE
Migrate to Xamarin Plugin instead of Forms

### ISSUE THREAD

**Issue by alexrainman** [EgorBo/Toasts.Forms.Plugin#35]
Can you remove Xamarin.Forms dependency and make it compatibel with Xamarin native projects and PCL?

I tried to do it myself by somehow get top activity context is not working.

**Comment by EgorBo** [comment]
@alexrainman that's the problem. I don't know how to get current activity in a simple way.

**Comment by alexrainman** [comment]
I know how to get current activity in really easy way. But it seems reflection ia noy working well from plugin in the pcl, i can share that code with you.

**Comment by EgorBo** [comment]
@alexrainman show me :smile: I don't need to do it in the PCL

**Comment by alexrainman** [comment]
I know you are not doing it in the pcl. I implemented in android but it seems is not resolved in the pcl.

**Comment by EgorBo** [comment]
@alexrainman so whats the method you use for that? :smile: The only way I see is a custom Activity class for all activities in a project.

**Comment by alexrainman** [comment]
You can get top activity multiple ways. Using reflection, using activity manager and using activitylifecycle callbacks. I tested the latest and its not woring. I changed the init function passing activity factory function but not working. Can you test activity manager?
ActivityManager am = (ActivityManager)context.getSystemService(Context.ACTIVITY_SERVICE);
ComponentName cn = am.getRunningTasks(1).get(0).topActivity; 
].

**Comment by EgorBo** [comment]
@alexrainman so i thought.
getRunningTasks doesn't look like a good solution: http://developer.android.com/reference/android/app/ActivityManager.html#getRunningTasks(int)
* This method was deprecated in API level 21.
* Note: this method is only intended for debugging and presenting task management user interfaces.

**Comment by alexrainman** [comment]
You right but the right way is the way that works.

**Comment by alexrainman** [comment]
Then, what about reflection? I will send you what i was trying in a few min. Thanks

**Comment by alexrainman** [comment]
Can you try this in your Android implementation?

public static Activity GetActivity(){
			
			Java.Lang.Class activityThreadClass = Java.Lang.Class.ForName("android.app.ActivityThread");
			Java.Lang.Object activityThread = activityThreadClass.GetMethod("currentActivityThread").Invoke(null);
			Java.Lang.Reflect.Field activitiesField = activityThreadClass.GetDeclaredField("mActivities");
			activitiesField.Accessible = true;

			var activities = (Java.Util.HashMap) activitiesField.Get(activityThread);

			foreach(Java.Lang.Object activityRecord in activities.Values()){
				
				Java.Lang.Class activityRecordClass = activityRecord.Class;
				Java.Lang.Reflect.Field pausedField = activityRecordClass.GetDeclaredField("paused");
				pausedField.Accessible = true;
				if(!pausedField.GetBoolean(activityRecord)) {					
					Java.Lang.Reflect.Field activityField = activityRecordClass.GetDeclaredField("activity");
					activityField.Accessible = true;
					var activity = (Activity) activityField.Get(activityRecord);
					return activity;
				}
			}

			return null;
		}

**Comment by EgorBo** [comment]
@alexrainman already have. It didn't work :cry:

**Comment by alexrainman** [comment]
and activity lifecycle callbacks? i get this in both: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

**Comment by alexrainman** [comment]
both this one and activity lifecycle callbacks trigger this: java.lang.reflect.InvocationTargetException

**Comment by alexrainman** [comment]
by the way, the problem is from PCL.

**Comment by alexrainman** [comment]
This is what i did.

 1. Add this to android implementation:

static Func<Activity> GetTopActivity;

public static void Init(Func<Activity> getTopActivity, IToastLayoutCustomRenderer customRenderer = null)
{
    GetTopActivity = getTopActivity;
    _customRenderer = customRenderer ?? new DefaultToastLayoutRenderer();
}

2. Change this:

 Activity currentActivity = Xamarin.Forms.Forms.Context as Activity;

to this:

 Activity currentActivity = GetTopActivity();

3. Add this class to your project:

public class ActivityMonitor : Java.Lang.Object, Application.IActivityLifecycleCallbacks {
	public static Activity CurrentTopActivity { get; protected set; }
	public virtual void OnActivityCreated(Activity activity, Bundle savedInstanceState) {
		CurrentTopActivity = activity;
	}
	public virtual void OnActivityResumed(Activity activity) {
		CurrentTopActivity = activity;
	}
	public virtual void OnActivityPaused(Activity activity) {}
	public virtual void OnActivityDestroyed(Activity activity) {}
	public virtual void OnActivitySaveInstanceState(Activity activity, Bundle outState) {}
	public virtual void OnActivityStarted(Activity activity) {}
	public virtual void OnActivityStopped(Activity activity) {}
}

4. Add this to Application class OnCreate:

RegisterActivityLifecycleCallbacks(new ActivityMonitor());
ToastsImplementation.Init(() => ActivityMonitor.CurrentTopActivity);

It works from Platform project but not from PCL. It is not a complete solution but at least it works.

**Comment by alexrainman** [comment]
Allan Ritchie is able to get Activity in his UserDialogs plugin https://github.com/aritchie/acr-xamarin-forms. Tried to do the same but it didnt work. He use static class to start Instance of plugin and somehow he is able to get current activity from PCL. What we are missing?

**Comment by EgorBo** [comment]
@alexrainman 
Init(Func getTopActivity
-- this is almost what I've planned to do :smile:
I'll take a look on it once I finish my current project.

**Comment by alexrainman** [comment]
Cool that i can help. I really love this plugin. Thanks.

**Comment by jamesmontemagno** [comment]
http://motzcod.es/post/133609925342/access-the-current-android-activity-from-anywhere  to grab the top activity is the best route :)

**Comment by alexrainman** [comment]
Inhave the plugin working without Forma dependency. I will add this and update my repo. Thanks @jamesmontemagno and @egorbo

**Comment by adamped** [comment]
Forms dependency removed in latest release.
