### ISSUE TITLE
Increase Height

### ISSUE THREAD

**Issue by cristiano939** [EgorBo/Toasts.Forms.Plugin#36]
Good Morning,
I have a question here:
When my messages are large, and it's not possible to reduce it,
it's possible to increase the height of the Toast Box ?

**Comment by adamped** [comment]
Not longer applicable as Toasts Plugin has been rewritten. 

Please file a new issue if you experience an problem with the new version.

More Info: https://xamarinhelp.com/toast-notifications-xamarin-forms/
