### ISSUE TITLE
Error when init in Xamarin.iOS AppDelegate class

### ISSUE THREAD

**Issue by stefan89** [EgorBo/Toasts.Forms.Plugin#4]
When I init the plugin in a Xamarin.Forms iOS project I get the following error:

Error MT0034: Cannot include both 'monotouch.dll' and 'Xamarin.iOS.dll' in the same Xamarin.iOS project - 'monotouch.dll' is referenced explicitly, while 'Xamarin.iOS.dll' is referenced by 'Toasts.Forms.Plugin.iOS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. (MT0034) (MyProjectName)

Initilization like:

                public override bool FinishedLaunching (UIApplication app, NSDictionary options)
		{
			Forms.Init ();

			ToastNotificatorImplementation.Init ();

			window = new UIWindow (UIScreen.MainScreen.Bounds);

			...
			return true;
		}

How could I solve this?

I am using Xamarin.Forms 1.3.0 (stable)

PS. thanks for sharing this awesome plugin

**Comment by Zeraceee** [comment]
I have the same issue, I want to use this plugin so bad but I have nullpointer on Android and this on iOS. Can confirm bug.

**Comment by EgorBo** [comment]
Let me take a look, I tested it on a sample with Unified API.

**Comment by vhugogarcia** [comment]
I'm getting an error on initialization on iOS: 

Xamarin.Forms.Init();//platform specific init
ToastNotificatorImplementation.Init(); //you can pass additional parameters here

I already added using Toasts.Forms.Plugins;
There is no namespace Toasts.Forms.Plugins.iOS

Am I missing something to add into specific platform? if yes what is? or is this a bug?

Thanks in advance, great work!

**Comment by Zeraceee** [comment]
@vhugogarcia You must add the nuget DLL of this plugin into both your IOS and Android projects. If you are only making an IOS app, you must add the DLL into your IOS project. Nuget should handle that for you.

**Comment by vhugogarcia** [comment]
@Zeraceee Thanks for your faster responder.

Actually, I added them on iOS and Android projects as well. See screenshots:

DLLs: http://i59.tinypic.com/15hyf6o.png
Autocomplete: http://i57.tinypic.com/ricj0n.png

Note: I'm using Xamarin.Forms 1.3.1 Unified API (Final release) - iOS and Android projects.

**Comment by stefan89** [comment]
@vhugogarcia  I just updated to Xamarin.Forms 1.3.1 and migrated my project to an unified project and now I also experience the same issue.  It does not recognise the required namespace anymore.

**Comment by Zeraceee** [comment]
@vhugogarcia 
On latest build, getting same issue (1.3.1). I hope the author can update, if not, I will fork and rebuild for you guys.

**Comment by EgorBo** [comment]
@Zeraceee, @stefan89, @vhugogarcia sorry guys, I'll try to manage with these issues once I be home (in a day or two).

**Comment by vhugogarcia** [comment]
Thanks @Zeraceee and @EgorBo

**Comment by TorbenK** [comment]
Awesome plugin. You have an idea on when you get this working for 1.3.1?

**Comment by Zeraceee** [comment]
@EgorBo any updates?

**Comment by stefan89** [comment]
@EgorBo did you already solved the issue?

**Comment by ceblanda** [comment]
@EgorBo I'm also getting the "Cannot include both 'monotouch.dll' and 'Xamarin.iOS.dll' in the same Xamarin.iOS project" issue = do you have any updates?

**Comment by ceblanda** [comment]
Turns out this is using the new unified API, and it's using new features of the API, so it can not easily be pulled back.
http://developer.xamarin.com/guides/cross-platform/macios/updating_ios_apps/

**Comment by stefan89** [comment]
Even in plugin version 1.0.8 it does not work in iOS.

Still can't find ToastNotificatorImplementation.Init();

**Comment by EgorBo** [comment]
Fixed in 1.0.1.12
