### ISSUE TITLE
Conflict between Toasts and StatusBar Height (UIKit.UIApplication.SharedApplication.StatusBarFrame.Height)

### ISSUE THREAD

**Issue by RogerHardiman** [EgorBo/Toasts.Forms.Plugin#40]
Using the Toasts.Forms.Plugin has an unexpected conflict with Xamarin.iOS asking the operating system for the height of the Status Bar.

In Xamarin Forms I ask the OS for the height of the Status Bar every time there is a SizeChanged event and then adjust my screen layout (the XamForms StackLayout padding)
I use UIKit.UIApplication.SharedApplication.StatusBarFrame.Height to get the height.

This works perfectly in my apps but fails after the first Toast has been generated using Toasts.Forms.Plugin.

Before the Toast, the call to UIKit.UIApplication.SharedApplication.StatusBarFrame.Height gives me 20 pixels for portrait and 0 pixels for landscape (on iPhone). On iPad it is always 20 pixels in both orientations.

After the Toast the call to UIKit.UIApplication.SharedApplication.StatusBarFrame.Height gives me 0 pixels for portrait and 20 pixels for landscape on iPhone,

Something has happened so that when Xamarin Forms and Xamarin.iOS asks for the height, it gets incorrect values if a Toast has been generated.

My code is like this in a Xamarin Forms app

	    	this.SizeChanged += (object sender, EventArgs e) => 
    			{
    				// iOS on phones hides the Status Bar in Landscape (iPad does not)
			        if (Device.OS == TargetPlatform.iOS) {
						int sbHeight = (int)UIKit.UIApplication.SharedApplication.StatusBarFrame.Height);
						stackLayout.Padding = new Thickness (0, sbHeight, 0, 0);
	    			}
    			};

Other tests...
I have tested with the pre release of 1.7.x.x and there is no change.
I have tested with the current Alpha of Xamarin.iOS 8.13.x.x  and no change.
ACR's Toast library works fine so currently use your library for Android and ACR for iOS

Thanks
Roger

**Comment by adamped** [comment]
@RogerHardiman - I can't seem to replicate this error. Any chance you provide a sample proj showing the behavior?

**Comment by RogerHardiman** [comment]
We can close this bug report down.

Tested today with the an updated Xamarin Platform (latest Xamarin Studio, Mono, Android and iOS libraries) and the problem is not showing up.
