### ISSUE TITLE
Document minimum iOS & Android version (crashing on iOS6.1).

### ISSUE THREAD

**Issue by trevoriancox** [EgorBo/Toasts.Forms.Plugin#43]
Xamarin Forms 1.4/1.5 supports iOS 6.1 (ref: https://developer.xamarin.com/guides/cross-platform/xamarin-forms/getting-started/installation/)

TWMessageBarManager is supposed to support iOS 6.0 or later. (ref: https://github.com/terryworona/TWMessageBarManager)

That being said, this is crashing for me on iOS6.1.

**Comment by adamped** [comment]
@trevoriancox - I will be documenting the minimum versions shortly. Looking over the statistics, while XF supports 6.1, considering its immensely small user base, its over 3 years old and other plugins / frameworks are dropping support for it, this plugin will also be dropping support for it. We will now only support iOS 7+

Apologies if you are still supporting iOS 6, this is just a free project I am helping in my limited spare time.
