### ISSUE TITLE
System.MissingMethodException: Method 'ViewTreeObserver.RemoveOnGlobalLayoutListener' not found.

### ISSUE THREAD

**Issue by tobiasschittkowski** [EgorBo/Toasts.Forms.Plugin#44]
When I use Toasts.Forms.Plugin V 1.0.6.18 on my Xamarin Forms Android App and I compile it with Android level 15 (4.0.3) and run it in a emulator running Android 4.0.3, I get this exception...

It is strange, should not 

           if (Build.VERSION.SdkInt < Build.VERSION_CODES.JellyBean)
                {
                    croutonView.ViewTreeObserver.RemoveGlobalOnLayoutListener(layoutListener);
                }
                else
                {
                    croutonView.ViewTreeObserver.RemoveOnGlobalLayoutListener(layoutListener);
                }

prevent such errors?

**Comment by adamped** [comment]
@tobiasschittkowski - I can't replicate the error when I have the minimum version set to API 15 and the compile set to API 23. This allows you to continue to run on API 15 devices. We will continue to support that configuration for the time being (even though as it stands, API 15 is on less than 3% of Android devices). 

But I can't support setting the Compile against 4.0.3.
