### ISSUE TITLE
Toast is compatible with the new Windows 8.1  projects? i am getting an error

### ISSUE THREAD

**Issue by guiwaltricke** [EgorBo/Toasts.Forms.Plugin#46]
The error: 

Adding 'Toasts.Forms.Plugin 1.0.6.18' to Useall.E2.Comercial.AV.Mobile.Windows.
Install-Package : Could not install package 'Toasts.Forms.Plugin 1.0.6.18'. You are trying to install this package into a project that targets 'WindowsPhoneApp,Version=v8.1', but the package does not contain 
any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package Toasts.Forms.Plugin -Version 1.0.6.18
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

Someone know about?
Thanks

**Comment by jamesmontemagno** [comment]
I believe it just supports WP 8 silverlight apps currently.

**Comment by adamped** [comment]
@guiwaltricke @jamesmontemagno - Windows Phone 8.1 is now supported in 2.0.0-pre1 (also supports UWP by default, though no specific UWP package has been created yet)
