### ISSUE TITLE
Question  for use this plugin

### ISSUE THREAD

**Issue by lima66** [EgorBo/Toasts.Forms.Plugin#48]
I want to use it in android dependecy  (ZXing barcode scanner), but it doesn't work. in iOS  works perfectly. Can you tell me how to operate it ?

Thanks very much for your plugin

**Comment by adamped** [comment]
I haven't used the ZXing barcode scanner, this is just a toasts plugin for each platform. If you need it to interact with another component you might want to check out the support on that components page.
