### ISSUE TITLE
Incompatible with Xamarin.Forms 1.3.1.6296

### ISSUE THREAD

**Issue by tomcrusader** [EgorBo/Toasts.Forms.Plugin#5]
I upgraded my project's nuget packages - Xamarin.Forms and Toasts Plugin. My Win Phone project then failed to build.

Uninstalling Toasts resolved the issue.

The error I got was:

    Cannot resolve dependency to assembly Xamarin.Forms.Core, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null because it has not been preloaded

**Comment by fonix232** [comment]
Remove the NuGet package and reinstall it :) 1.3.1 broke almost all plugins, but re-initializing them will solve the issue.

**Comment by EgorBo** [comment]
I have just published 1.0.0.6 for 1.3.1 :-) I'm sorry for the delay.
