### ISSUE TITLE
System.IO.FileNotFoundException: /Icons/icon-error.png does not exist

### ISSUE THREAD

**Issue by Bonelol** [EgorBo/Toasts.Forms.Plugin#50]
Throw this error after update to 1.0.9.21

Error	365	System.IO.FileNotFoundException: /Users/local_admin/Library/Caches/Xamarin/mtbs/builds/MyMobileiOS/6a1077279d715fb26949d0c771bd85c4/obj/iPhone/Debug/Icons/icon-error.png does not exist
File name: '/Users/local_admin/Library/Caches/Xamarin/mtbs/builds/MyMobileiOS/6a1077279d715fb26949d0c771bd85c4/obj/iPhone/Debug/Icons/icon-error.png'
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, Boolean overwrite) <0x19ff7f0 + 0x00333> in <filename unknown>:0 
  at Xamarin.MacDev.Tasks.SmartCopyTaskBase.CopyFile (System.String source, System.String target, System.String targetItemSpec) <0x38e0640 + 0x000c7> in <filename unknown>:0 
  at Xamarin.MacDev.Tasks.SmartCopyTaskBase.Execute () <0x38dfe20 + 0x00227> in <filename unknown>:0 	C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	377	3	MySIT.Mobile.iOS

**Comment by BeatKe** [comment]
Same problem here...

**Comment by MilenPavlov** [comment]
Had similar issue few months ago, deleted builds/yourappname folder on mac machine and then rebuild the app. I believe it's related to Xamarin bug...

**Comment by adamped** [comment]
Thanks @MilenPavlov 

@Bonelol @BeatKe - if deleting existing builds and doing a clean don't resolve the issue, please let me know and I will look into it further.

**Comment by Bonelol** [comment]
@adamped , I deleted build folder in /Library/Caches/Xamarin/mtbs, it didn't help. Currently what I do is to copy icons from Toasts project to my one, then I can build successfully.

**Comment by marcojak** [comment]
@adamped I deleted everything but this didn't help.

Is it possible to fix this problem?

**Comment by adamped** [comment]
@marcojak - I will look at it soon. Apologies just overwhelmed at the moment while I finish up my over commitments on some community related work :)

From a quick look at the project, I don't know why that specific icon is causing a problem. It is set to the same build action as the other ones, nor are there a pre or post build operation for those icons. 

Can you copy Bonelol's suggestion of copying into your own project to get around the issue temporarily? https://github.com/EgorBo/Toasts.Forms.Plugin/tree/master/Toasts.Forms.Plugin.iOS/Resources/Icons

**Comment by BlueFire-LLC** [comment]
@adamped - I found the bug. If you move the icons in the Toasts.Forms.Plugin.iOS Icons folder out and place them directly in the Resources folder, then modify DefaultMessageBarStyleSheet.cs icon constants and remove the Icon/ folder reference, it works. Seems there is a VS/Xamarin.IOS bug with using folders in the Resources folder. Could you please let me know when you have a new version with this fix out on Nuget? Thanks, Mark.

**Comment by hgross** [comment]
+1
A fixed version on NuGet is much appreciated :)

**Comment by adamped** [comment]
@hgross @BlueFire-LLC @marcojak @Bonelol - 2.0.0-pre2 has been released, which switched these resources to bundled resources instead of content. It has fixed the error on my machine.

However I am also now running  Xamarin 4, Cycle 6 Service Release 1 in Beta (the stable release is meant to be sometime next week). There is a bug fix in there that is very similar to what we are experiencing here and this may have also contributed to the fix.

You can try -pre2 and see how it goes. If not, try the Beta channel for Xamarin (or wait until next week for the stable) and get the latest and that will fix the issue.
