### ISSUE TITLE
Assembly could not be found

### ISSUE THREAD

**Issue by VictorGrunn** [EgorBo/Toasts.Forms.Plugin#58]
Using the latest version on Nuget. Trying to set up the Toasts plugin in iOS gives the following error:

Reference to type 'Toasts.IToastNotificator' claims it is defined assembly 'Toasts.Forms.Plugin.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null', but it could not be found.

This is from

DependencyService.Register\<Toasts.ToastNotificatorImplementation\>();

in AppDelegate.cs

**Comment by MatthewGerber** [comment]
Same problem here. Version 2.0.0 worked for me, but I got this error after upgrading to 2.0.1.

**Comment by patook** [comment]
+1 exact same error. Tried removing and re-installing it to no avail. Also looked for it under Plugin.Toasts

**Comment by MatthewGerber** [comment]
Workaround for me was to simply downgrade to 2.0.0, which still works fine.

**Comment by adamped** [comment]
Apologies for the issue, will try to get a new version out soon. However version 2.0.1 was just an update for WinRT and not the other platforms hence version 2.0.0 is the latest version also for iOS and Android.

**Comment by BlueFire-LLC** [comment]
Same here. Downgrade works but is a PITA when an update fails and you waste valuable dev time trying to figure out what you did.

**Comment by tonci77** [comment]
Hy,

Same problem 'here'...

What's the right procedure for downgrade, 'how to....' ?


Thank's in advance.

**Comment by patook** [comment]
I forgot the exact syntax but in the “Add Nuget packages” you search for something like

 

Toasts.Plugin version:*

**Comment by adamped** [comment]
Apologies all - 2.0.2 just released and tested locally on my machine, each platform, WinRT, WinPhone, Android, iOS all working. Let me know if it resolves this issue and I will close it out.

**Comment by BlueFire-LLC** [comment]
Works great. Thanks.
