### ISSUE TITLE
Question/Request

### ISSUE THREAD

**Issue by De4th69** [EgorBo/Toasts.Forms.Plugin#6]
Hi,
first of all, thank you for this plugin. It's really cool.
So my question: Would it be possible to create a notification with an ActivityIndicator?
I would contribute to this but currently I can't support all 3 platforms (VS2012/Win7)

**Comment by EgorBo** [comment]
@De4th69 not sure I understand you - you want to place an ActivityIndicator instead of image?

**Comment by De4th69** [comment]
Yes that's what I meant. I would use that so I can show my users that they triggered an download which is progressed in a background thread.

**Comment by adamped** [comment]
Not on our radar to implement unless many further requests are made. I feel like this is breaking many mobile UI/UX principles and that any activity indicator needs to be on the page not in a toast.
