### ISSUE TITLE
Any e.t.a. for NotifySticky?

### ISSUE THREAD

**Issue by 14skywalker** [EgorBo/Toasts.Forms.Plugin#65]
I have some use cases for it ;-)

**Comment by adamped** [comment]
No eta at the moment. Though we welcome pull requests if you wanted to help implement it.

**Comment by 14skywalker** [comment]
Thanks Adam. I'll see what I can do.

**Comment by adamped** [comment]
Not longer applicable as Toasts Plugin has been rewritten.

More Info: https://xamarinhelp.com/toast-notifications-xamarin-forms/
