### ISSUE TITLE
 Android.Views.InflateException

### ISSUE THREAD

**Issue by oaestella** [EgorBo/Toasts.Forms.Plugin#66]
Tried to use this Plugin for a Xamarin Forms Shared Project. I have set the Toast Init after the Xamarin.Forms.Init() as stated in the docs. An exception of type "Android.Views.InflateException: <merge /> can be used only with a valid ViewGroup root and attachToRoot=true" throws.

 Is there something wrong with what Im doing?
Im using FormsAppCompatActivity by the way.

**Comment by bentmar** [comment]
Same here, app crashes at startup with the same error (+ Binary XML error, cannot use </Merge>...) (not even toasting), also using ForsmAppCompatActivity. Is there any fix planned for this?

**Comment by junalmeida** [comment]
+1 here

**Comment by parasmk** [comment]
Same problem. None to answer???

**Comment by lucascc26** [comment]
Any news on this?
I'm facing the same issue.

Thanks.

**Comment by Spierki** [comment]
+1

**Comment by adamped** [comment]
Not longer applicable as Toasts Plugin has been rewritten. 

Please file a new issue if you experience an problem with the new version.

More Info: https://xamarinhelp.com/toast-notifications-xamarin-forms/
