### ISSUE TITLE
Dismiss possible?

### ISSUE THREAD

**Issue by stefandevo** [EgorBo/Toasts.Forms.Plugin#7]
Is it possible to add the possibility that when the user "ticks" the toast that it is dismissed (even when the duration is not yet expired)?

**Comment by Zaxter** [comment]
I believe this already works in the current version, atleast with iOS. 
I wasn't able to get it to work on android though.

**Comment by EgorBo** [comment]
@stefandevo fixed for android and uploaded a package to nuget, thanks for feedback!
