### ISSUE TITLE
iOS customization has no Context

### ISSUE THREAD

**Issue by RanaInside** [EgorBo/Toasts.Forms.Plugin#70]
in iOS, we have to use MessageBarStyleSheet to style toast; so without any renderer, we can't customize the layout; furthermore, MessageBarStyleSheet has no context that is being passed for styling.

Can I also request the class to have an override to disable title?

thanks guys for the great work.

**Comment by adamped** [comment]
Not longer applicable as Toasts Plugin has been rewritten. 

Please file a new issue if you experience an problem with the new version.

More Info: https://xamarinhelp.com/toast-notifications-xamarin-forms/
