### ISSUE TITLE
NullReferenceException in Android

### ISSUE THREAD

**Issue by aji27** [EgorBo/Toasts.Forms.Plugin#71]
My app crashes when I try to use this plugin. (Xamarin Forms App, PCL)

I do this in my MainActivity:
`            DependencyService.Register<IToastNotificator, ToastNotificatorImplementation>();
            ToastNotificatorImplementation.Init(this);`
Then I do this:
`            var notificator = DependencyService.Get<IToastNotificator>();
            await notificator.Notify(ToastNotificationType.Success, "test", "test", TimeSpan.FromSeconds(5.0d));`

Can someone help me please? I am really stuck here.

Edit: +added stacktrace

`System.NullReferenceException: Object reference not set to an instance of an object
  at Plugin.Toasts.DefaultToastLayoutRenderer.Render (Android.App.Activity activity, ToastNotificationType type, System.String title, System.String description, System.Object context) [0x00036] in C:\Users\adamp\Source\Repos\Toasts.Forms.Plugin\Toasts.Forms.Plugin.Droid\DefaultToastLayoutRenderer.cs:28 
  at Plugin.Toasts.ToastNotificatorImplementation.Notify (ToastNotificationType type, System.String title, System.String description, TimeSpan duration, System.Object context, Boolean clickable) [0x00027] in C:\Users\adamp\Source\Repos\Toasts.Forms.Plugin\Toasts.Forms.Plugin.Droid\ToastNotificatorImplementation.cs:27 `

Kind regards,
Aji27

**Comment by adamped** [comment]
If you go to your Resources.Designer.cs file and delete everything inside of it, then rebuild, does that solve the problem?

**Comment by aji27** [comment]
Thank you for your quick response. I will be working on this peoject on the next wednesday, so I will answer you then.
Have a nice weekend.
Kind regards,aji27


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Adam <notifications@github.com>
Datum: 09.04.2016  02:19  (GMT+01:00)
An: "EgorBo/Toasts.Forms.Plugin" <Toasts.Forms.Plugin@noreply.github.com>
Cc: aji27 <ajanth.kandasamy@hotmail.com>
Betreff: Re: [EgorBo/Toasts.Forms.Plugin] NullReferenceException in Android (#71)

If you go to your Resources.Designer.cs file and delete everything inside of it, then rebuild, does that solve the problem?

---

**Comment by aji27** [comment]
Hi adamped
I found out what the problem was. Your hint helped me. The Resources.designer.cs was not generated and was not included in the project, so it wouldn't even compile.

1. Generate Resources.designer.cs: http://stackoverflow.com/questions/18346430/xamarin-android-how-to-rebuild-resource-designer-cs
2. Include Resources.designer.cs into your project and set the build action to 'compile'
3. Build and run

Thank you for your help. This issue can be closed.

Have a nice day.
aji27

**Comment by mkrampf** [comment]
I am having the same issue, but the proposed solution doesn't fix it for me. I've regenerated the resource file (and it's included in the solution and build action is set to compile) but still get an exception. I have no other issues with resources in that file.

Here is the stack trace (as far as I can tell it's identical to the OP's stack trace):

```
05-03 16:56:00.200 I/MonoDroid( 1646): UNHANDLED EXCEPTION:
05-03 16:56:00.200 I/MonoDroid( 1646): System.NullReferenceException: Object reference not set to an instance of an object.
05-03 16:56:00.200 I/MonoDroid( 1646):   at Plugin.Toasts.DefaultToastLayoutRenderer.Render (Android.App.Activity activity, ToastNotificationType type, System.String title, System.String description, System.Object context) [0x00036] in C:\Users\adamp\Source\Repos\Toasts.Forms.Plugin\Toasts.Forms.Plugin.Droid\DefaultToastLayoutRenderer.cs:28 
05-03 16:56:00.200 I/MonoDroid( 1646):   at Plugin.Toasts.ToastNotificatorImplementation.Notify (ToastNotificationType type, System.String title, System.String description, TimeSpan duration, System.Object context, Boolean clickable) [0x00027] in C:\Users\adamp\Source\Repos\Toasts.Forms.Plugin\Toasts.Forms.Plugin.Droid\ToastNotificatorImplementation.cs:27 
```

Any suggestions?

**Comment by adamped** [comment]
@mkrampf - to help debug where this issue is occurring can you use this ToastRenderer, pass that through and then see where in the code this breaks. This is the default custom renderer but we will be able to get an exact breaking point with the code in your solution.

https://raw.githubusercontent.com/dcasbonne/Toasts.Forms.Plugin/patch-1/Toasts.Forms.Plugin.Droid/DefaultToastLayoutRenderer.cs

**Comment by mkrampf** [comment]
Thank you for your prompt reply! Sorry, I actually found the problem. I was creating toasts from a shared project, which had the correct Toasts.Forms references (so everything built fine), but it turns out that the lower level startup project also needed a reference to Toasts.Forms in order to create the correct resource entries.
