### ISSUE TITLE
Cannot locate resource from 'ms-appx:///FrameStyle.xaml'.

### ISSUE THREAD

**Issue by mvladm14** [EgorBo/Toasts.Forms.Plugin#74]
When running the winRT application the following exception is thrown:

```
An exception of type 'System.Runtime.InteropServices.COMException' occurred in FeedBackIO.UWP.exe but was not handled in user code

WinRT information: Cannot locate resource from 'ms-appx:///FrameStyle.xaml'.

Additional information: Unspecified error
```

**Comment by adamped** [comment]
In your WinRT application you should see a FrameStyle.xaml.

If you don't try reinstalling the NuGet Package. If that still fails to work, please let me know.

But as a work around, you can go to the source code and download FrameStyle.xaml and place it in the root of the WinRT project.

**Comment by mvladm14** [comment]
Apparently the FrameStyle.xaml file is within the application. 

However, it is not included in the project. I noticed this by cloning the repository.

Reinstalling the NuGet package did not help (as expected).

A simple fix would be to include the file in the WinRT.csproj:

<Page Include="FrameStyle.xaml">
     <Generator>MSBuild:Compile</Generator>
     <SubType>Designer</SubType>
</Page>

Hope this helps,
Vlad

**Comment by odahan** [comment]
Same error, but the "fix" does not work, uwp project is saying the file does not exist when it is reloaded (after modifying csproj file).
uninstalling/reinstalling the plugin does not work too.

**Comment by johnshardman** [comment]
I hit the same thing on UWP. Simply added the FrameStyle.xaml to my own project as per Adam's response above. Works fine.

**Comment by philipogorman** [comment]
![uwp-toast](https://cloud.githubusercontent.com/assets/3401258/16625264/3c1ee9c2-4369-11e6-9533-8857bdf8ddd2.PNG)
Fix works for me add FrameStyle.xaml to the root of the UWP project and rebuild

**Comment by odahan** [comment]
Fix for me : use the source code in each project instead of the nuget package... That works with some minor corrections. Do not forget to set the xaml file as "page" for the build.
But this is not a good way to fix the problem, this must be done in the nuget package.

**Comment by aherrick** [comment]
Manually adding the FrameStyle.xaml to my UWP project worked fine for me. Thanks!

**Comment by adamped** [comment]
Not longer applicable as Toasts Plugin has been rewritten. 

Please file a new issue if you experience an problem with the new version.

More Info: https://xamarinhelp.com/toast-notifications-xamarin-forms/
