### ISSUE TITLE
Can Not Show Notification Icons

### ISSUE THREAD

**Issue by sercandumansiz** [EgorBo/Toasts.Forms.Plugin#76]
Hello I just implemented Toasts to my Xamarin Forms Project , everything works fine but the icons are not show up. Should I do something for the Icons ? Is there anyway to do this ? 

Thanks.

**Comment by parth7676** [comment]
@sercandumansiz  @EgorBo I also have the same problem.Ever thing works fine but icons are not show up in ios.

**Comment by parth7676** [comment]
@sercandumansiz I solved the problem, In my case, I have just downloaded the images in the Resources/icons folder and it worked. You may also try downloading images in **Android-Resources/Drawable** and **IOS- Resource/icons**

**Comment by aherrick** [comment]
I too just manually added the icons in an Icons folder I created. Works great!

**Comment by fvermeulen** [comment]
@EgorBo I only have the problem on ios...  Can that maybe come to a building failure on your side. Maybe link all problem?

**Comment by adamped** [comment]
Not longer applicable as Toasts Plugin has been rewritten. 

Please file a new issue if you experience an problem with the new version.

More Info: https://xamarinhelp.com/toast-notifications-xamarin-forms/
