### ISSUE TITLE
HideAll hangs app on Android

### ISSUE THREAD

**Issue by eyadon** [EgorBo/Toasts.Forms.Plugin#77]
Xamarin Forms v2.2.0.45, Toasts.Forms.Plugin v2.0.4, Android API 22
Attached really simple example.  Tap the button a couple times to get a few toasts in the queue, then tap one.

```

public App()
        {
            // The root page of your application
            MainPage = new ContentPage
            {
                Content = new StackLayout
                {
                    VerticalOptions = LayoutOptions.Center,
                    Children = {
                        new Label {
                            XAlign = TextAlignment.Center,
                            Text = "Welcome to Xamarin Forms!"
                        },
                        new Button {Command = new Command(Notify), Text = "Notify"}
                    }
                }
            };
        }

        private async void Notify()
        {
            var notificator = DependencyService.Get<IToastNotificator>();
            bool tapped = await notificator.Notify(ToastNotificationType.Info,
                "Something", "You pressed the button!", TimeSpan.FromSeconds(2));
            if (tapped)
            {
                notificator.HideAll();
                MainPage.BackgroundColor = MainPage.BackgroundColor==Color.Blue? Color.Black : Color.Blue;
            }
        }
```

**Comment by NVentimiglia** [comment]
Confirm this, Noticed that any call to the service on Android froze my device. I noticed this after I moved my popup logic from a Xamarin Forms view class and into a non-forms (service) class.

**Edit**

I resolved this issue by removing the static reference in my service class. Works if I get a new IToastNotifier for each call.

**Comment by cmeeren** [comment]
I too experience the Android app freezing if there are toasts in the queue when `HideAll()` is called.

The below code will crash:

```
var notificator = DependencyService.Get<IToastNotificator>();
notificator.Notify(ToastNotificationType.Error, "Error", "Something went wrong", TimeSpan.FromSeconds(3));
notificator.Notify(ToastNotificationType.Error, "Error", "Something else went wrong", TimeSpan.FromSeconds(4));
await Task.Delay(2000);
notificator.HideAll();
```

If you change the first Toast to last only 1 second instead of 3 (so that it gets dismissed before calling `HideAll()`), it works.

I haven't had the chance to test on iOS. Using Xamarin.Forms 2.3.1.114.

**Comment by adamped** [comment]
Not longer applicable as Toasts Plugin has been rewritten. 

Please file a new issue if you experience an problem with the new version.

More Info: https://xamarinhelp.com/toast-notifications-xamarin-forms/

**Comment by cmeeren** [comment]
Brilliant, thanks!
