### ISSUE TITLE
Feature request: Bottom position

### ISSUE THREAD

**Issue by stefandevo** [EgorBo/Toasts.Forms.Plugin#8]
Would it be easy to add the possibility the show the toast at the bottom of the screen?

**Comment by EgorBo** [comment]
Nice idea!

**Comment by De4th69** [comment]
Is there some update for this? It would be nice to have :)

**Comment by rubgithub** [comment]
Awaiting this implementation.

**Comment by highplains** [comment]
+1

**Comment by adamped** [comment]
I believe Snackbar does this as default but we use Crouton. Its a great idea and one we will implement but we need to think this one out a little.

**Comment by mkrampf** [comment]
+1
