### ISSUE TITLE
Feature Request: On Fullscreen, bar from top of screen

### ISSUE THREAD

**Issue by Asnanon** [EgorBo/Toasts.Forms.Plugin#80]
While programming apps using the fullscreen mode feature (hidden status bar), it still leaves space for the status bar, which doesn't look as nice as it would, if when it would come borderless from the top of the screen.

**Comment by adamped** [comment]
Not longer applicable as Toasts Plugin has been rewritten. 

Please file a new issue if you experience an problem with the new version.

More Info: https://xamarinhelp.com/toast-notifications-xamarin-forms/
