### ISSUE TITLE
uwp notification not displaying

### ISSUE THREAD

**Issue by asulwer** [EgorBo/Toasts.Forms.Plugin#81]
what am i missing?  

`var notificator = DependencyService.Get<Plugin.Toasts.IToastNotificator>();`
`bool tapped = await notificator.Notify(Plugin.Toasts.ToastNotificationType.Info, "Info", "Test Description", TimeSpan.FromSeconds(2));`

this does not display anything!  this is running on my dev box (not mobile device)

**Comment by adamped** [comment]
Any errors or anything in the Debug console to go off?

**Comment by asulwer** [comment]
nope

**Comment by adamped** [comment]
Not longer applicable as Toasts Plugin has been rewritten. 

Please file a new issue if you experience an problem with the new version.

More Info: https://xamarinhelp.com/toast-notifications-xamarin-forms/
