### ISSUE TITLE
App is resized if StatusBar is hidden

### ISSUE THREAD

**Issue by jernelson7** [EgorBo/Toasts.Forms.Plugin#83]
Our app hides the ios status bar. When a notification is shown, it is offset from the top by ~20px. We might be able to live with that, but what is unacceptable is the entire app is then shrunk by that amount, and we're left with 20px of blank space at the top. I believe this is due to MessageBarManager._messageBarOffset, which is readonly. Can you please expose an override for this?

Edit: We would also need to override MessageBarViewController.PrefersStatusBarHidden.

**Comment by adamped** [comment]
Not longer applicable as Toasts Plugin has been rewritten. 

Please file a new issue if you experience an problem with the new version.

More Info: https://xamarinhelp.com/toast-notifications-xamarin-forms/
