### ISSUE TITLE
UWP / Cannot locate resource from 'ms-appx:///FrameStyle.xaml'.

### ISSUE THREAD

**Issue by odahan** [EgorBo/Toasts.Forms.Plugin#84]
Hi, 
When launching UWP app there is an exception :

"Unspecified error:
Cannot locate resource from 'ms-appx:///FrameStyle.xaml'."

Uninstall , reinstall, clean solution, rebuild, nothing is working.
(and the file is not in bin/x86/debug/AppX).

The plugin runs correctly on iOS and Android.

Any idea, patch or trick to avoid this error ?

**Comment by aherrick** [comment]
+1

**Comment by freddyisag** [comment]
Hi,
If I take a look into the compiled binary (Toasts.Forms.Plugin.WinRT.dll), all resources are missing. And a quick look into the project file tells me, the resources are not embedded...
Can you please fix it and provide a new version? Thanks!
Freddy

**Comment by freddyisag** [comment]
Hi,
As a workaround for the mentioned issue, take the following files from another (e.g. WinPhone 8.1) project and copy it to your UWP Project:

    - FameStyle.xaml (Build Action: Page, Copy To Output Directory: Do not copy, Custom Tool: MSBuild:Compile)
    - Icons\error.png (Build Action: Content, Copy To Output Directory: Do not copy, Custom Tool: )
    - Icons\info.png (Build Action: Content, Copy To Output Directory: Do not copy, Custom Tool: )
    - Icons\success.png (Build Action: Content, Copy To Output Directory: Do not copy, Custom Tool: )
    - Icons\warning.png (Build Action: Content, Copy To Output Directory: Do not copy, Custom Tool: )

This worked for my UWP project ...

Freddy

**Comment by gviddy** [comment]
Yes would love an official fix for this. Thanks for the work around whilst we wait though. ;)

**Comment by adamped** [comment]
The toasts plugin has now been completely rewritten (3.0.0-beta1) to use the native platform notification systems, which means it removes all of these types of issues. Any feedback welcome: https://xamarinhelp.com/toast-notifications-xamarin-forms/

**Comment by EaranMaleasi** [comment]
I know that this is closed and also abandoned but so far I have no other option but to use this. I have the same error as described above, but I cannot use the workaround from @ghost as I am somehow unable to create win8.1 or WinPhone 8.1 Projects with said files. Also switching to 3.0.0+ does not work as on Android these Toasts just show a little bit of Title, about one or two words, and nothing else (I'll create an Issue for this some time in the future). Also my users are used to the style and color scheme of the toasts. Is there any other way to get 2.0.4 to work on UWP?

**Comment by adamped** [comment]
@EaranMaleasi - you can download the source code and directly add it to your project. You can download the repo from this point, which is still in 2.0.4. https://github.com/EgorBo/Toasts.Forms.Plugin/tree/e5ee33a7172f23e2403c6ce275f24553f393c519
