### ISSUE TITLE
UWP can't call init when using AppShell  pattern for side menu

### ISSUE THREAD

**Issue by NPadrutt** [EgorBo/Toasts.Forms.Plugin#85]
Hi

I have an Page as my content root to display a side menu as shown in official UWP samples. You can see it here:

https://github.com/MoneyFox/MoneyFox/blob/master/Src/MoneyFox.Windows/Views/AppShell.xaml

Now when I call the Init Method on ToastNotificatorImplementation the apps crashes because it tries to cast AppShell to Frame.

Is there any way to override that behaviour in the way that it doesn't try to parse the Window.Current.Content to Frame but for example I can inherit from the base class and override the behavior that it parses the content to an AppShell and uses the MyAppFrame to do the operations?

**Comment by adamped** [comment]
The toasts plugin has now been completely rewritten (3.0.0-beta1) to use the native platform notification systems, which means it removes all of these types of issues. Any feedback welcome: https://xamarinhelp.com/toast-notifications-xamarin-forms/
