### ISSUE TITLE
Not working in Xamarin.Forms version 2.3

### ISSUE THREAD

**Issue by fab971** [EgorBo/Toasts.Forms.Plugin#86]
In Xamarin.Forms version 2.3 toasts has a top offset and a twitch motion. 
Did you plan to make it be compatible with v 2.3?

PS: Not sure I used the correct english words to explain

**Comment by adamped** [comment]
The toasts plugin has now been completely rewritten (3.0.0-beta1) to use the native platform notification systems, which means it removes all of these types of issues. Any feedback welcome: https://xamarinhelp.com/toast-notifications-xamarin-forms/

**Comment by candidodmv** [comment]
Hi @adamped , but this updates will break previous versions?
I'm using the current stable version, and works on iOS but on Android nothing do when i call `Notify` even   no errros, could you help me to solve this problem?

Thanks

**Comment by candidodmv** [comment]
Hi @adamped  I did solve the problem with this code:
Sorry, by annoying
```
MainActivity.instance.RunOnUiThread(() => {
 var notificator = DependencyService.Get<IToastNotificator>();
if (notificator != null)
{
notificator.Notify(ToastNotificationType.Info, title, desc, TimeSpan.FromSeconds(5));
}
});
```
