### ISSUE TITLE
Toasts.Forms.Plugin v 2.04 issue with text truncation

### ISSUE THREAD

**Issue by faceoffers28** [EgorBo/Toasts.Forms.Plugin#87]
I'm not sure if this is a UWP issue, but after an upgrade I am experiencing an issue with truncating text.

I upgraded from Toasts.Forms.Plugin v.1.0.6.18 to 2.04 in order for the plugin to work in my new Windows 10 UWP app. 

For example, here is my notification when a user does not enter both a user and password as login.

"Email address and password are both required."

Now, I receive a notification that looks like this.

"Email address and password..."

Is this a bug or have I not fully implemented the new plugin?

Thanks!

**Comment by adamped** [comment]
@faceoffers28 - I would actually recommend you use a dialog (DisplayAlert) for displaying this information to users as it is critical and the user can not proceed without doing something. I tend to find Toasts better as just a friendly notification mechanism that if they miss it, its not critical.

I will have a look at the truncating text but I think a dialog would be a better UI in your scenario.

**Comment by faceoffers28** [comment]
Thanks for the advice. I really appreciate it. 

I just tested my iOS app and it is working just fine. I'm using notifications all over the app, so I need to figure this out.

I'm running Xamarin.Forms v 2.2.0.31 targeting PCL 259. Thanks!

**Comment by adamped** [comment]
@faceoffers28 - if you need to change it now, you might want to look at FrameStyle.xaml that would have been put in the root of your UWP project. Inside there is the default template for how the Toasts are displayed. You can change this to style it how you want. Will most likely be quicker than waiting for me to get around updating component.

**Comment by faceoffers28** [comment]
@adamped This is the FrameStyle file that I'm using. It didn't install when I upgraded the plugin, so I just manually added it. 

https://github.com/EgorBo/Toasts.Forms.Plugin/blob/master/Toasts.Forms.Plugin.WinRT/FrameStyle.xaml

I've tried to edit the file, but with my limited knowledge, nothing seems to work. Can you point me in the right direction? Thanks in advance!

**Comment by adamped** [comment]
Apologies you need to create a new renderer. Copy this, modify it and inject it in the init https://github.com/EgorBo/Toasts.Forms.Plugin/blob/master/Toasts.Forms.Plugin.WinRT/DefaultToastLayoutRenderer.cs

**Comment by faceoffers28** [comment]
@adamped OK, I've implemented all the files and edited the DefaultToastLayoutRenderer file to allow word wrapping. I had to use a bunch of breaks, but I finally found where the code is breaking for me. If I comment out the _lastUsedInstance == null lines as shown below, the code breaks on the next line. If I don't comment out the lines, the program returns with no notification. This is located in the ToastPromptsHostControler.cs file.

public static void EnqueueItem(UIElement content, Action<bool> submitAction, Brush bgBrush, bool tappable, TimeSpan timeout, bool showCloseButton)
        {
            //if (_lastUsedInstance == null)
            //    return;

            _lastUsedInstance._notificationQueue.Enqueue(new NotificationItem(content, bgBrush, submitAction, tappable, timeout, showCloseButton));
            _lastUsedInstance.TryDequeue();
        } 

I can see that the toast seems to get created correctly. This lines is complete, but both context and out brush are null. This line is found in the ToastNotificatorImplementation.cs.

var element = _customRenderer.Render(type, title, description, context, out brush);

Any idea on how to fix this? Thanks!

**Comment by faceoffers28** [comment]
@adamped If I don't comment out the  _lastUsedInstance == null lines, the code seems to end here, but no notification displays.  

return taskCompletionSource.Task;

This is found in the ToastNotificatorImplementation.cs file.

Does this code work for you? Any help is much appreciated. Thanks!

**Comment by faceoffers28** [comment]
@adamped OK, I finally got it to work. This is the first time I have implemented a custom renderer, so I was out of my league from the word go. I did, however learn a lot, which is always best. I ended up only adding 1 file to my UWP Project in order for this to work. I added DefaultToastLayoutRender.cs with a using Plugin.Toasts; statement. I then edited these lines.

 `var descTb = new TextBlock
            {
                Text = description,
                VerticalAlignment = VerticalAlignment.Center,
                Margin = new Thickness(12, -4, 0, 0),
                TextTrimming = TextTrimming.WordEllipsis,
                //TextWrapping = TextWrapping.NoWrap,
                TextWrapping = TextWrapping.Wrap,
                Foreground = new SolidColorBrush(Colors.White),
                FontSize = 14
            };
`
NOTE: If I choose FontSize 16, it doesn't wrap. I have no idea why.

I then used this code to inject the DefaultToastLayoutRenderer. This was no where in the instructions, so not knowing what I was really doing, I just kept trying stuff until I got it to work.

Xamarin.Forms.DependencyService.Register<ToastNotificatorImplementation>();
            ToastNotificatorImplementation.Init(stackSize: 3, customRenderer: new DefaultToastLayoutRenderer());

Hope this helps someone else.

**Comment by adamped** [comment]
Glad to see you got it working and thank you for sharing your solution.
