### ISSUE TITLE
Android: Space at the top when toolbar is shown

### ISSUE THREAD

**Issue by wize1** [EgorBo/Toasts.Forms.Plugin#88]
Is it possible to get rid of space on top of the toast?
Not sure what it relates to, maybe because i have toolbar on that view.

[Screenshot](https://yadi.sk/i/2644T7TruLWUn)

**Comment by adriancho5692** [comment]
Having the same problem. Also using toolbar with AppCompat in Xamarin Forms.

**Comment by adamped** [comment]
The toasts plugin has now been completely rewritten (3.0.0-beta1) to use the native platform notification systems, which means it removes all of these types of issues. Any feedback welcome: https://xamarinhelp.com/toast-notifications-xamarin-forms/

**Comment by aherrick** [comment]
Is there not a solution for this in 2.0.4? Seeing the same thing. Unfortunately not a huge fan of the native notifications.
