### ISSUE TITLE
[3.0] Add "DismissText" and "ViewText" options to AndroidOptions

### ISSUE THREAD

**Issue by diego-suarez** [EgorBo/Toasts.Forms.Plugin#89]
Right now, the text "Dismiss" when showing the snackbar is hardcoded.
I think is necessary to have the option to configure it, specially when using i18n on the app.

**Comment by adamped** [comment]
Thanks for the PR. I will keep this open for the moment so I can track changes to the next release.

**Comment by adamped** [comment]
Deployed in 3.1.0
