### ISSUE TITLE
Feature Request: no title

### ISSUE THREAD

**Issue by stefandevo** [EgorBo/Toasts.Forms.Plugin#9]
Would be nice if you could define (of evaluate) that there is no title and that all text is rendered from the top. Leaving the title empty leaves an empty line in the toast.

**Comment by EgorBo** [comment]
@stefandevo good idea, I'll implement it soon. BTW, but you can also achieve the same by using custom renderers for toast, see  https://github.com/EgorBo/Toasts.Forms.Plugin#customization

**Comment by adamped** [comment]
Someone will be providing us a pull request soon to implement this, though we don't have a firm timeline.
