### ISSUE TITLE
.HideAll() not found in version 3.0.0

### ISSUE THREAD

**Issue by luisfernandomoraes** [EgorBo/Toasts.Forms.Plugin#91]
Why this method was removed?

**Comment by adamped** [comment]
The HideAll method wasn't even implemented on the WIndows Platform and the toasts only show for 7 seconds, hence I couldn't see the point in adding a HideAll method to the new version. Is there a need to hide the toast notification within its 7 second display window? If there is a solid use case I can look into adding it in.

**Comment by luisfernandomoraes** [comment]
Yes, there is a need. When I have to shoot several toasts in sequence, I need the last, if still alive, hide it, and then show the latest. In this context, I can not wait 7 seconds. Thank you in advance.

**Comment by adamped** [comment]
Neither iOS or Android really has anyway to hide a toast that is currently displaying. It can cancel scheduled toasts, or remove notifications from the notification center but nothing to do with a currently displaying toast.

To me having such a rapid run of notifications one after the other then hiding the first ones shown seems odd because why not just ignore the first few toasts if you are going to hide them quickly before the user sees them anyway?

**Comment by luisfernandomoraes** [comment]
Using this flow you suggested, may overcrowd the app interface, making the usability of some features that are hidden behind the old toasts.

For example: A list of products to add to shopping list while in the User will add products to the shopping list, the toasts are displayed, if there is no HideAll () to hide the old toasts, the products screen start will be hidden by the toasts.

**Comment by adamped** [comment]
I have implemented a CancelAllDelivered() method. This will remove all from the Notification Center on UWP, iOS and Android.

It will hide any toasts currently showing only on 
Android or UWP. There is no way for me to remove it on iOS. If you find a way please let me know and I can implement it.

It is the best I can do. I did search and look around the API for a while and nothing would remove the currently displaying toast faster than 7 seconds.

This package is now uploaded as 3.1.0

**Comment by EmilAlipiev** [comment]
Hi @adamped,

I was wondering how it is implemented here for IOS https://github.com/aritchie/notifications
can we get this done similar way? 

thanks
