### ISSUE TITLE
Resourcedesigner finds 0 refrences to this plugin

### ISSUE THREAD

**Issue by bentmar** [EgorBo/Toasts.Forms.Plugin#94]
'Resource.Drawable' does not contain a definition for 'abc_ic_star_half_black_36dp'	

i get this with "i think" every resource that this plugin has.
Runnig on XF 2.1.0.6529

**Comment by adamped** [comment]
Hi

I believe this would only be an issue directly on the android project. Do
you have android.support.v7.appcompat installed and if so what version.

Thanks
Adam

On Wednesday, October 5, 2016, bentmar <notifications@github.com> wrote:
> 'Resource.Drawable' does not contain a definition for
'abc_ic_star_half_black_36dp'
>
> i get this with "i think" every resource that this plugin has.
> Runnig on XF 2.1.0.6529
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/-sCRrtEoRVZmDkX88HyytrSuCIdYVZ6ks2CjxuyVQ4Mre0BJi8pM_2aedo_byhQp5hd-DhDx9Qk3q5anlc0HQuMRgbA5v-mO_zjhZpui9ZX_JcO4XmAY3IBpuPSrxWXURESXaqVC6oaw9mutUXR1oosAkEPoHg=s0-d-e1-ft#https://github.com/notifications/beacon/ANCg1p4i4ZSmiUbzxQU-M8pqIXYtKuiDks5qwmc6gaJpZM4KNxK6.gif
>

**Comment by bentmar** [comment]
yes, 23.0.1.3

**Comment by adamped** [comment]
Android Toasts package requires at least 23.3.0. Apologies I should have
specified that in the Nuget package, I will do that in the next upgrade of
the package.

As such you need to upgrade to Xamarin Forms 2.2.0 or higher. 2.2.0 came
out 6 months ago and references 23.3.0. Ideally I would recommend upgrading
to 2.3.2 as all the versions up to that point include a huge number of bug
fixes and they all reference 23.3.0 of the support library.

Thanks
Adam

**Comment by bentmar** [comment]
Oh okay!

In the current project we can´t upgrade any higher atm because of a bug in appearing/dissapearing events, it will finally be solved in the upcoming release :D (trust we, i want to update so bad).

fyi, i managed to get it "working" in my current project, but it doesnt relly fix it (deleting failing rows in resourcedesigner.cs) 

Thank for the response!
