### ISSUE TITLE
Cannot install to PCL 

### ISSUE THREAD

**Issue by zjxeditor** [EgorBo/Toasts.Forms.Plugin#96]
Hi, I just want to update the package from v2.0.4 to v3.1.0. It failed to install this package to PCL with profile 111.

**Comment by adamped** [comment]
Hi Jx

Your project needs to be upgraded to .NET standard as along with many
others, everything is being converted over to .NET standard. If you don't
know much about it, I wrote a blog post about upgrading your projects.
https://xamarinhelp.com/dot-net-standard-pcl-xamarin-forms/

Thanks
Adam
