### ISSUE TITLE
Error on build with 3.0.0

### ISSUE THREAD

**Issue by thfaix** [EgorBo/Toasts.Forms.Plugin#97]
At first I tried to install version 3.1.0 but it didn't work with PCL (without .NET Standard) so I came back to 3.0.0 an now I can't build the project.
As long as the project doesn't have a using of the Plugin.Toast in the PCL, the project can still build; After that I have this error : The "ResolveLibraryProjectImports" task failed unexpectedly.

**Comment by adamped** [comment]
These errors tend to be related to VS or Xamarin, not so much a particular version. 

Try installing 3.0.0 and make sure you have the latest version of Xamarin, then restart VS or XS, open the project again and try to build.
