### ISSUE TITLE
Remove Xamarin.Forms dependency

### ISSUE THREAD

**Issue by alexrainman** [EgorBo/Toasts.Forms.Plugin#98]
I can help with that but i guess you can do it guys. It doesn't make sense to have Forms dependency.

**Comment by alexrainman** [comment]
Considering that the new functionality use each of native platforms notification systems.

**Comment by alexrainman** [comment]
Also, i believe Forms has a really uncertain future. The latest couple of releases are really buggy.

**Comment by jbravobr** [comment]
Really buggy? Could you please list some one of those bugs?

Em sáb, 8 de out de 2016 às 19:59, Alex Rainman <notifications@github.com>
escreveu:

**Comment by alexrainman** [comment]
I am not talking about this plugin, i'm talking about Xamarin.Forms itself. These are the bugs i am talking about:

1- We couldn’t build an app using Xamarin.Android 7 and Android SDK 7. Lot of crashes and weird exceptions like this one:

```
[art] Late-enabling -Xcheck:jni
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.slbdev.LoadChart.Droid, PID: 1776
[AndroidRuntime] java.lang.RuntimeException: Unable to instantiate application md527a7919e283623d91a69ee9a78351a60.MainApplication: java.lang.ClassNotFoundException: Didn't find class "md527a7919e283623d91a69ee9a78351a60.MainApplication" on path: DexPathList[[zip file "/data/app/com.slbdev.LoadChart.Droid-1/base.apk"],nativeLibraryDirectories=[/data/app/com.slbdev.LoadChart.Droid-1/lib/x86, /data/app/com.slbdev.LoadChart.Droid-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
[AndroidRuntime] 	at android.app.LoadedApk.makeApplication(LoadedApk.java:578)
[AndroidRuntime] 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680)
[AndroidRuntime] 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:102)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:148)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:5417)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
[AndroidRuntime] Caused by: java.lang.ClassNotFoundException: Didn't find class "md527a7919e283623d91a69ee9a78351a60.MainApplication" on path: DexPathList[[zip file "/data/app/com.slbdev.LoadChart.Droid-1/base.apk"],nativeLibraryDirectories=[/data/app/com.slbdev.LoadChart.Droid-1/lib/x86, /data/app/com.slbdev.LoadChart.Droid-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
[AndroidRuntime] 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
[AndroidRuntime] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
[AndroidRuntime] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
[AndroidRuntime] 	at android.app.Instrumentation.newApplication(Instrumentation.java:981)
[AndroidRuntime] 	at android.app.LoadedApk.makeApplication(LoadedApk.java:573)
[AndroidRuntime] 	... 9 more
[AndroidRuntime] 	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.slbdev.LoadChart.Droid-1/base.apk
[AndroidRuntime] 		at dalvik.system.DexFile.openDexFileNative(Native Method)
[AndroidRuntime] 		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
[AndroidRuntime] 		at dalvik.system.DexFile.<init>(DexFile.java:80)
[AndroidRuntime] 		at dalvik.system.DexFile.<init>(DexFile.java:59)
[AndroidRuntime] 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:279)
[AndroidRuntime] 		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
[AndroidRuntime] 		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
[AndroidRuntime] 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
[AndroidRuntime] 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:65)
[AndroidRuntime] 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:58)
[AndroidRuntime] 		at android.app.LoadedApk.getClassLoader(LoadedApk.java:376)
[AndroidRuntime] 		at android.app.LoadedApk.makeApplication(LoadedApk.java:568)
[AndroidRuntime] 		... 9 more
[AndroidRuntime] 	Suppressed: java.lang.ClassNotFoundException: md527a7919e283623d91a69ee9a78351a60.MainApplication
[AndroidRuntime] 		at java.lang.Class.classForName(Native Method)
[AndroidRuntime] 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
[AndroidRuntime] 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
[AndroidRuntime] 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
[AndroidRuntime] 		... 12 more
[AndroidRuntime] 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
[Process] Sending signal. PID: 1776 SIG: 9
```
This happened and multiple projects.

2- Android and iOS launcher icon restarts the app instead of bringing it from background but the app keeps it’s state if you bring it back from Recents (Xamarin.iOS 10/Xamarin.Android 7 plus XForms 2.3.1 and up).

3- Xamarin Studio and iOS Simulator is broken: With the first release of Xamarin.iOS i was able to run the app in debug mode only one time, after that i had to go to the process of closing the simulator and open it again. The first time trying to open it, i saw this behavior:

![screen shot 2016-09-20 at 3 24 49 pm](https://cloud.githubusercontent.com/assets/3793554/19216649/1fedd36a-8d8a-11e6-8566-48c957578548.png)


A i had to close it again and the second time i saw this:

![screen shot 2016-09-20 at 3 25 19 pm](https://cloud.githubusercontent.com/assets/3793554/19216650/2c2f7020-8d8a-11e6-9fea-7eec90bb7694.png)

Then i the third intent, finally the simulator runs.

It seems it has been partially fixed in the latest release but, the connection with simulator still broken. Simulator is running but Xamarin Studio cannot connect to it after some time. I have to restart it manually to make it work and it takes more time than normal to run.

4- Xamarin.Forms ListView context actions make the app crashes when you swipe one cell and try to swipe another one:

```
Value cannot be null.
Parameter name: gestureRecognizer

at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/data/lanes/3818/ad1cd42d/source/xamarin-macios/src/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Users/builder/data/lanes/3818/ad1cd42d/source/xamarin-macios/src/UIKit/UIApplication.cs:63 
```

This issue is there no matter which version of XForms you have on top of Xamarin.iOS 10.

5- Xamarin.iOS 10/Xamarin.Android 7 plus any version of Forms bigger than 2.3.0.107 breaks the app. Home screen is like a screenshot. It doesn’t respond to touch events. Also ListView doesn’t populate with data.

6- You can build and deploy a Xamarin.iOS app using Xamarin.iOS 9 to iOS 10 (which you cannot do with XCode :)

It seems the combination of Xamarin.Forms with Xamarin.Android 7 and Xamarin.iOS 10 is a full mess, and i am Xamarin lover but it's the truth. I am moving away from Forms.

Combination of packages that works for me:

- Xamarin Studio 6.1.1.15
- Xamarin.Android 6.1.2
- Android SDK 23 with build-tools 23.0.3
- Xamarin.iOS 10.0.1.10 (with the mentioned issues with Simulator and Forms ListView context actions)
- Xamarin.Forms 2.3.0.107

**Comment by adamped** [comment]
@alexrainman - this plugin doesn't have a Xamarin Forms dependency. For android it does require the Android.Support.Design library because it uses Snackbar but the Forms dependency was removed starting with version 2.0.

If you are referring to plugin ID of Toasts.Forms.Plugin, unfortunately its just a legacy naming convention I have to keep because I can't change it.

**Comment by alexrainman** [comment]
Thats what i was talking about. Thanks
