### ISSUE TITLE
Cannot install version 3.1.0

### ISSUE THREAD

**Issue by alexrainman** [EgorBo/Toasts.Forms.Plugin#99]
Is version 3.1.0 not compatible with PCL? Cannot install in Profile49 neither 78.

**Comment by adamped** [comment]
Anything at version 3.0 or above is NetStandard only. If you have an old project that you can't upgrade to netstandard, you will need to stay with version 2.0.4.

**Comment by alexrainman** [comment]
3.0 and above? I was able to install version 3.0 in a PCL project.

**Comment by adamped** [comment]
Well if you could you weren't meant to :)

**Comment by alexrainman** [comment]
I just changed the profile to 78 and i it works :)

**Comment by adamped** [comment]
awesome, glad to know that you can still install it on Profile78. Not sure why 78 is working will be useful to others.
